"""Configuration for running Brian2 simulations from SONATA configs."""

from typing import ClassVar

from pydantic import Field

from obi_one.core.block import Block
from obi_one.core.path import NamedPath
from obi_one.core.schema import SchemaKey, UIElement
from obi_one.core.single import SingleConfigMixin
from obi_one.scientific.library.info_scan_config.config import InfoScanConfig


class Brian2SimulationFromSonataScanConfig(InfoScanConfig):
    """Configuration for running a Brian2 simulation from SONATA config files.

    Takes the output of generate-simulations (simulation_config.json) and
    executes the simulation using the Brian2 simulator with point neuron models.
    """

    name: ClassVar[str] = "Brian2 Simulation from SONATA"
    description: ClassVar[str] = (
        "Run a Brian2 simulation from SONATA config files generated by generate-simulations"
    )
    single_coord_class_name: ClassVar[str] = "Brian2SimulationFromSonataSingleConfig"

    class Initialize(Block):
        """Initialization parameters for Brian2 simulation."""

        simulation_config_path: NamedPath | list[NamedPath] = Field(
            title="Simulation Config Path",
            description="Path to the SONATA simulation_config.json file "
            "generated by generate-simulations.",
            json_schema_extra={
                # SchemaKey.UI_ELEMENT: UIElement.PATH,
            },
        )

        integration_method: str | list[str] = Field(
            default="linear",
            title="Brian2 Integration Method",
            description="Brian2 integration method override. If empty, the method "
            "stored in the node group's dynamics_params is used.",
            json_schema_extra={
                # SchemaKey.UI_ELEMENT: UIElement.STRING_PARAMETER_SWEEP,
            },
        )

    initialize: Initialize = Field(
        title="Initialize",
        description="Initialization parameters for the Brian2 simulation.",
        json_schema_extra={
            SchemaKey.UI_ELEMENT: UIElement.BLOCK_SINGLE,
        },
    )


class Brian2SimulationFromSonataSingleConfig(
    Brian2SimulationFromSonataScanConfig, SingleConfigMixin
):
    """Single-coordinate configuration for a Brian2 simulation from SONATA."""
