"""Task to run a Brian2 simulation from SONATA config files.

Reads a SONATA ``simulation_config.json`` (generated by generate-simulations or
by a bespoke converter), builds a Brian2 point-neuron network from the
referenced SONATA circuit, applies stimuli / recordings / manipulations
through the mirrored ``brian2_blocks`` handlers, and writes SONATA-compatible
output files (``spikes.h5`` and ``voltage.h5``).
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import TYPE_CHECKING, Any, ClassVar

import h5py
import numpy as np
from pydantic import PrivateAttr

from obi_one.core.task import Task
from obi_one.scientific.tasks.brian2_simulation_from_sonata.brian2_blocks.base import (
    Brian2FeatureNotSupportedError,
)
from obi_one.scientific.tasks.brian2_simulation_from_sonata.brian2_blocks.manipulations import (
    get_connection_override_handler,
    get_modification_handler,
)
from obi_one.scientific.tasks.brian2_simulation_from_sonata.brian2_blocks.recordings import (
    Brian2SpikeRecording,
    get_report_handler,
)
from obi_one.scientific.tasks.brian2_simulation_from_sonata.brian2_blocks.stimuli import (
    get_input_handler,
)
from obi_one.scientific.tasks.brian2_simulation_from_sonata.config import (
    Brian2SimulationFromSonataSingleConfig,  # noqa: TC001
)

if TYPE_CHECKING:
    from collections.abc import Iterable

L = logging.getLogger(__name__)

_OUTPUT_DIR = "brian2_output"
_SPIKES_FILE = "spikes.h5"
_VOLTAGE_FILE = "voltage.h5"

_VOLT_PARAM_NAMES = frozenset({"v_0", "v_rst", "v_th", "E_L", "V_reset", "V_th", "V_m"})
_SECOND_PARAM_NAMES = frozenset(
    {"t_mbr", "tau", "tau_m", "tau_syn_ex", "tau_syn_in", "t_ref", "rfc", "t_dly"}
)


class Brian2SimulationFromSonataTask(Task):
    """Execute a Brian2 simulation from a SONATA simulation config."""

    config: Brian2SimulationFromSonataSingleConfig

    SPIKES_FILE_NAME: ClassVar[str] = _SPIKES_FILE
    VOLTAGE_FILE_NAME: ClassVar[str] = _VOLTAGE_FILE

    _sonata_config: dict = PrivateAttr(default_factory=dict)
    _circuit_config: dict = PrivateAttr(default_factory=dict)
    _node_sets: dict = PrivateAttr(default_factory=dict)
    _node_population_name: str = PrivateAttr(default="")
    _neuron_group: Any = PrivateAttr(default=None)
    _synapses: Any = PrivateAttr(default=None)
    _brian2_objects: list = PrivateAttr(default_factory=list)
    _recording_devices: dict[str, Any] = PrivateAttr(default_factory=dict)
    _spike_monitor: Any = PrivateAttr(default=None)
    _v_0_applied_from_dynamics_params: bool = PrivateAttr(default=False)

    def execute(
        self,
        *,
        db_client: Any = None,  # noqa: ARG002
        entity_cache: bool = False,  # noqa: ARG002
        execution_activity_id: str | None = None,  # noqa: ARG002
    ) -> None:
        """Run the Brian2 simulation."""
        try:
            import brian2 as b2  # noqa: PLC0415
        except ImportError as e:
            msg = (
                "The 'brian2' package is required to run Brian2 simulations. "
                "Install it with: pip install brian2"
            )
            raise ImportError(msg) from e

        sim_config_path = Path(self.config.initialize.simulation_config_path.path).resolve()
        output_dir = Path(self.config.coordinate_output_root) / _OUTPUT_DIR
        output_dir.mkdir(parents=True, exist_ok=True)

        self._load_configs(sim_config_path)

        # Fully isolate this simulation from any previous Brian2 state in the
        # same Python process (e.g. prior scan coordinates or a reference
        # run_trial run in the same notebook). `start_scope()` alone only
        # resets the magic namespace; `device.reinit + activate` also resets
        # the runtime device state so the seeded RNG stream is reproducible.
        b2.device.reinit()
        b2.device.activate()
        b2.start_scope()
        self._configure_brian2(b2)

        self._build_network(b2)
        self._apply_conditions(b2)
        # Create recording devices before stimuli so the object-creation order
        # matches the reference Drosophila_brain_model.create_model(...)/poi(...)
        # flow and Brian2's internal RNG bookkeeping stays aligned.
        self._apply_reports(b2)
        self._apply_inputs(b2, sim_config_path.parent)
        self._warn_connection_overrides()
        self._warn_modifications()

        net = b2.Network(self._neuron_group, self._synapses, *self._brian2_objects)

        tstop_raw = float(self._sonata_config.get("run", {}).get("tstop", 1000.0))
        tstop = tstop_raw * b2.ms
        L.info("Starting Brian2 simulation for %.1f ms", tstop_raw)
        net.run(duration=tstop, report="text")
        L.info("Brian2 simulation completed")

        self._write_output(output_dir, b2)

    # ----- config loading ----------------------------------------------------

    def _load_configs(self, sim_config_path: Path) -> None:
        """Load simulation_config.json, circuit_config.json, and node_sets.json."""
        with sim_config_path.open(encoding="utf-8") as f:
            self._sonata_config = json.load(f)

        network_path = self._sonata_config.get("network")
        if network_path:
            circuit_path = self._resolve_path(
                network_path, self._sonata_config.get("manifest", {}), sim_config_path.parent
            )
            with circuit_path.open(encoding="utf-8") as f:
                self._circuit_config = json.load(f)
            self._resolve_circuit_paths(circuit_path.parent)
        elif "networks" in self._sonata_config:
            self._circuit_config = self._sonata_config
            self._resolve_circuit_paths(sim_config_path.parent)
        else:
            L.warning("No 'network' field in simulation config; circuit will not be loaded.")

        node_sets_file = self._sonata_config.get("node_sets_file")
        if node_sets_file:
            ns_path = self._resolve_path(
                node_sets_file, self._sonata_config.get("manifest", {}), sim_config_path.parent
            )
            if ns_path.exists():
                with ns_path.open(encoding="utf-8") as f:
                    self._node_sets = json.load(f)

    @staticmethod
    def _resolve_path(path_str: str, manifest: dict, base_dir: Path) -> Path:
        resolved = path_str
        for var, value in (manifest or {}).items():
            key = var.lstrip("$")
            resolved = resolved.replace(f"${key}", str(value))
        p = Path(resolved)
        if not p.is_absolute():
            p = (base_dir / p).resolve()
        return p

    def _resolve_circuit_paths(self, base_dir: Path) -> None:
        """Resolve ``$BASE_DIR`` and other manifest variables to absolute paths."""
        manifest = self._circuit_config.get("manifest", {})
        resolved = {}
        for key, raw_value in manifest.items():
            k = key.lstrip("$")
            val = str(raw_value)
            if "$BASE_DIR" in val:
                val = val.replace("$BASE_DIR", ".")
            resolved[k] = str((base_dir / val).resolve())

        def _substitute(obj: Any) -> Any:
            if isinstance(obj, dict):
                return {k: _substitute(v) for k, v in obj.items()}
            if isinstance(obj, list):
                return [_substitute(e) for e in obj]
            if isinstance(obj, str) and "$" in obj:
                result = obj
                for var, path in resolved.items():
                    result = result.replace(f"${var}", path)
                return result
            return obj

        self._circuit_config = _substitute(self._circuit_config)

    # ----- brian2 setup ------------------------------------------------------

    def _configure_brian2(self, b2: Any) -> None:
        run = self._sonata_config.get("run", {})
        dt_ms = float(run.get("dt", 0.1))
        b2.defaultclock.dt = dt_ms * b2.ms
        seed = run.get("random_seed")
        if seed is not None:
            b2.seed(int(seed))

    # ----- network build -----------------------------------------------------

    def _build_network(self, b2: Any) -> None:
        """Build the Brian2 network from the SONATA circuit HDF5 files."""
        nodes_confs = self._circuit_config.get("networks", {}).get("nodes", [])
        if not nodes_confs:
            msg = "No 'networks.nodes' entries in circuit_config."
            raise Brian2FeatureNotSupportedError(msg)

        nodes_entry = nodes_confs[0]
        populations = nodes_entry.get("populations", {})
        if not populations:
            with h5py.File(nodes_entry["nodes_file"], "r") as f:
                populations = {name: {"type": "point_neuron"} for name in f["nodes"]}
        if len(populations) != 1:
            msg = "The Brian2 port currently supports only single-population circuits."
            raise Brian2FeatureNotSupportedError(msg)

        self._node_population_name = next(iter(populations))
        node_data = self._load_node_population(
            nodes_entry["nodes_file"], self._node_population_name
        )

        self._neuron_group = self._make_neuron_group(b2, node_data)
        self._synapses = self._make_synapses(b2)

    @staticmethod
    def _load_node_population(nodes_file: str, population_name: str) -> dict:
        with h5py.File(nodes_file, "r") as f:
            pop = f[f"nodes/{population_name}"]
            n_nodes = int(pop["node_type_id"].shape[0])
            group_ids = pop["node_group_id"][:]
            if not (group_ids == 0).all():
                msg = "The Brian2 port currently supports only single-group (0) node populations."
                raise Brian2FeatureNotSupportedError(msg)

            grp0 = pop["0"]
            dynamics = grp0["dynamics_params"]
            per_neuron: dict[str, np.ndarray] = {}
            scalars: dict[str, Any] = {}
            for key in dynamics:
                ds = dynamics[key]
                val = ds[()] if ds.shape == () else (ds[0] if ds.shape == (1,) else ds[:])
                if isinstance(val, bytes):
                    val = val.decode()
                if isinstance(val, np.ndarray):
                    per_neuron[key] = val
                else:
                    scalars[key] = val
        return {
            "n_nodes": n_nodes,
            "per_neuron_params": per_neuron,
            "scalar_params": scalars,
        }

    def _make_neuron_group(self, b2: Any, node_data: dict) -> Any:
        scalars = node_data["scalar_params"]
        if "eqs" not in scalars:
            msg = "dynamics_params is missing scalar string 'eqs' (Brian2 equations)."
            raise Brian2FeatureNotSupportedError(msg)

        eqs = scalars["eqs"]
        eq_th = scalars.get("eq_th", "v > v_th")
        eq_rst = scalars.get("eq_rst", "v = v_rst")
        method = self.config.initialize.integration_method or scalars.get("method", "linear")

        declared = set()
        for line in eqs.splitlines():
            stripped = line.strip()
            if ":" in stripped and not stripped.startswith("d"):
                declared.add(stripped.split(":")[0].strip().split("=")[0].strip())

        extra_decls = []
        for name in node_data["per_neuron_params"]:
            if name in declared:
                continue
            unit = _infer_unit_str(name)
            extra_decls.append(f"{name} : {unit} (constant)")
        full_eqs = eqs + ("\n" + "\n".join(extra_decls) if extra_decls else "")

        neu = b2.NeuronGroup(
            N=node_data["n_nodes"],
            model=full_eqs,
            method=method,
            threshold=eq_th,
            reset=eq_rst,
            refractory="rfc" if "rfc" in node_data["per_neuron_params"] else False,
            name="brian2_sonata_neurons",
        )

        unit_map = {"volt": b2.volt, "second": b2.second, "1": 1}
        for name, values in node_data["per_neuron_params"].items():
            unit = unit_map[_infer_unit_str(name)]
            setattr(neu, name, values * unit)

        if "v_0" in node_data["per_neuron_params"]:
            neu.v = node_data["per_neuron_params"]["v_0"] * b2.volt
            self._v_0_applied_from_dynamics_params = True
        if "g" in full_eqs:
            neu.g = 0 * b2.volt

        L.info(
            "Built NeuronGroup with %d neurons, per-neuron params: %s",
            node_data["n_nodes"],
            sorted(node_data["per_neuron_params"].keys()),
        )
        return neu

    def _make_synapses(self, b2: Any) -> Any:
        edges_confs = self._circuit_config.get("networks", {}).get("edges", [])
        if not edges_confs:
            L.warning("No 'networks.edges' entries in circuit_config; skipping recurrent synapses.")
            return b2.Synapses(
                self._neuron_group,
                self._neuron_group,
                model="w : volt",
                on_pre="g += w",
                name="brian2_sonata_synapses",
            )

        edges_entry = edges_confs[0]
        populations = edges_entry.get("populations", {})
        if not populations:
            with h5py.File(edges_entry["edges_file"], "r") as f:
                populations = {name: {"type": "chemical"} for name in f["edges"]}
        edge_pop = next(iter(populations))

        with h5py.File(edges_entry["edges_file"], "r") as f:
            pop = f[f"edges/{edge_pop}"]
            source = pop["source_node_id"][:]
            target = pop["target_node_id"][:]
            grp0 = pop["0"]
            scalar_params: dict[str, Any] = {}
            per_edge: dict[str, np.ndarray] = {}
            for key in grp0:
                ds = grp0[key]
                if not isinstance(ds, h5py.Dataset):
                    continue
                if ds.shape == ():
                    val = ds[()]
                    scalar_params[key] = val.decode() if isinstance(val, bytes) else val
                else:
                    per_edge[key] = ds[:]

        on_pre = scalar_params.get("on_pre", "g += syn_weight")
        syn_model = scalar_params.get("syn_model", "syn_weight : volt")

        syn = b2.Synapses(
            self._neuron_group,
            self._neuron_group,
            model=syn_model,
            on_pre=on_pre,
            name="brian2_sonata_synapses",
        )
        syn.connect(i=source.astype(int), j=target.astype(int))
        if "syn_weight" in per_edge:
            syn.syn_weight = per_edge["syn_weight"] * b2.volt
        if "delay" in per_edge:
            syn.delay = per_edge["delay"] * b2.second
        elif "delay" in scalar_params:
            syn.delay = float(scalar_params["delay"]) * b2.second

        L.info("Built Synapses population '%s' with %d edges", edge_pop, len(source))
        return syn

    # ----- config-driven pieces ---------------------------------------------

    def _apply_conditions(self, b2: Any) -> None:
        """Apply SONATA ``conditions`` to the Brian2 network.

        For Brian2 point-neuron circuits the per-neuron ``v_0`` in
        ``dynamics_params`` is authoritative, so a global ``conditions.v_init``
        must not override it — a redundant assignment would desync the initial
        state from the reference simulator and perturb Brian2's RNG bookkeeping.
        """
        conditions = self._sonata_config.get("conditions", {})
        v_init_mv = conditions.get("v_init")
        if v_init_mv is None or self._neuron_group is None:
            return
        if self._v_0_applied_from_dynamics_params:
            L.info(
                "Skipping conditions.v_init=%s mV: per-neuron v_0 from dynamics_params "
                "already initialized neu.v",
                v_init_mv,
            )
            return
        self._neuron_group.v = float(v_init_mv) * b2.mV

    def _apply_inputs(self, b2: Any, config_dir: Path) -> None:
        inputs = self._sonata_config.get("inputs", {})
        for input_name, input_config in inputs.items():
            module = input_config.get("module", "")
            resolved_config = dict(input_config)
            if module == "synapse_replay":
                spike_file = resolved_config.get("spike_file")
                if spike_file:
                    sp = Path(spike_file)
                    if not sp.is_absolute():
                        sp = (config_dir / spike_file).resolve()
                    resolved_config["spike_file"] = str(sp)
            try:
                handler = get_input_handler(resolved_config)
                handler.apply(
                    input_name,
                    resolved_config,
                    self._neuron_group,
                    self._node_population_name,
                    self._node_sets,
                    self._brian2_objects,
                    b2,
                )
                L.info("Applied input '%s' (module=%s)", input_name, module)
            except Brian2FeatureNotSupportedError as e:
                L.warning("Input '%s': %s", input_name, e)

    def _apply_reports(self, b2: Any) -> None:
        reports = self._sonata_config.get("reports", {})
        for report_name, report_config in reports.items():
            try:
                handler = get_report_handler(report_config)
                device = handler.apply(
                    report_name,
                    report_config,
                    self._neuron_group,
                    self._node_population_name,
                    self._node_sets,
                    self._brian2_objects,
                    b2,
                )
                self._recording_devices[report_name] = device
                L.info("Applied report '%s'", report_name)
            except Brian2FeatureNotSupportedError as e:
                L.warning("Report '%s': %s", report_name, e)

        self._spike_monitor = Brian2SpikeRecording().apply(
            "spikes",
            {},
            self._neuron_group,
            self._node_population_name,
            self._node_sets,
            self._brian2_objects,
            b2,
        )

    def _warn_connection_overrides(self) -> None:
        overrides = self._sonata_config.get("connection_overrides", [])
        for override in overrides:
            name = override.get("name", "unnamed")
            try:
                handler = get_connection_override_handler(override)
                handler.apply(override, self._synapses, self._neuron_group, self._node_sets, None)
            except Brian2FeatureNotSupportedError as e:
                L.warning("Connection override '%s': %s", name, e)

    def _warn_modifications(self) -> None:
        conditions = self._sonata_config.get("conditions", {})
        modifications = conditions.get("modifications", [])
        for mod in modifications:
            name = mod.get("name", "unnamed")
            try:
                handler = get_modification_handler(mod)
                handler.apply(mod, self._synapses, self._neuron_group, self._node_sets, None)
            except Brian2FeatureNotSupportedError as e:
                L.warning("Modification '%s': %s", name, e)

        mechanisms = conditions.get("mechanisms", {})
        if mechanisms:
            L.info(
                "SONATA conditions.mechanisms (%d entries) are NEURON-specific "
                "and ignored in Brian2.",
                len(mechanisms),
            )

    # ----- output ------------------------------------------------------------

    def _write_output(self, output_dir: Path, b2: Any) -> None:
        self._write_spike_output(output_dir, b2)
        self._write_voltage_output(output_dir, b2)

    def _write_spike_output(self, output_dir: Path, b2: Any) -> None:
        if self._spike_monitor is None:
            return
        spike_file = output_dir / _SPIKES_FILE
        trains = self._spike_monitor.spike_trains()

        pop_name = self._node_population_name
        ids_list: list[int] = []
        times_list: list[float] = []
        for nid, times in trains.items():
            if len(times) == 0:
                continue
            for t in np.asarray(times / b2.second):
                ids_list.append(int(nid))
                times_list.append(float(t) * 1000.0)

        times_arr = np.asarray(times_list, dtype=np.float64)
        ids_arr = np.asarray(ids_list, dtype=np.uint64)
        order = np.argsort(times_arr)
        times_arr = times_arr[order]
        ids_arr = ids_arr[order]

        with h5py.File(spike_file, "w") as f:
            grp = f.create_group(f"spikes/{pop_name}")
            grp.create_dataset("timestamps", data=times_arr)
            grp.create_dataset("node_ids", data=ids_arr)
            grp["timestamps"].attrs["units"] = "ms"
        L.info("Spike output written to %s (%d spikes)", spike_file, len(times_arr))

    def _write_voltage_output(self, output_dir: Path, b2: Any) -> None:
        voltage_devices: Iterable = [
            (name, dev)
            for name, dev in self._recording_devices.items()
            if dev is not None and hasattr(dev, "record")
        ]
        if not voltage_devices:
            return

        voltage_file = output_dir / _VOLTAGE_FILE
        with h5py.File(voltage_file, "w") as f:
            for report_name, sm in voltage_devices:
                recorded = np.asarray(sm.record, dtype=np.uint64)
                times_ms = np.asarray(sm.t / b2.ms, dtype=np.float64)
                data_mv = np.asarray(sm.v / b2.mV, dtype=np.float64)

                grp = f.create_group(f"reports/{report_name}")
                grp.create_dataset("senders", data=recorded)
                grp.create_dataset("timestamps", data=times_ms)
                grp.create_dataset("data", data=data_mv)
                grp["timestamps"].attrs["units"] = "ms"
                grp["data"].attrs["units"] = "mV"
        L.info("Voltage output written to %s", voltage_file)


def _infer_unit_str(param_name: str) -> str:
    if param_name in _VOLT_PARAM_NAMES:
        return "volt"
    if param_name in _SECOND_PARAM_NAMES:
        return "second"
    return "1"
