services:
  test:
    profiles: [test]
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    platform: linux/amd64  # because of pyflagser
    command:
    - sh
    - -cx
    - |
      python -m pytest
    volumes:
    - ./tests:/code/tests
    env_file: .env.test-docker
