SHELL := /bin/bash

export ENVIRONMENT ?= dev
export APP_NAME := obi-one
export APP_VERSION := $(shell git describe --abbrev --dirty --always --tags)
export COMMIT_SHA := $(shell git rev-parse HEAD)
export IMAGE_NAME ?= $(APP_NAME)
export IMAGE_TAG := $(APP_VERSION)
export IMAGE_TAG_ALIAS := latest
ifneq ($(ENVIRONMENT), prod)
	export IMAGE_TAG := $(IMAGE_TAG)-$(ENVIRONMENT)
	export IMAGE_TAG_ALIAS := $(IMAGE_TAG_ALIAS)-$(ENVIRONMENT)
endif

.PHONY: help install install-docs serve-docs compile-deps upgrade-deps check-deps format lint build publish test-local test-docker run-local run-docker destroy install-bluerecording

define load_env
	# all the variables in the included file must be prefixed with export
	$(eval ENV_FILE := .env.$(1))
	@echo "Loading env from $(ENV_FILE)"
	$(eval include $(ENV_FILE))
endef

help:  ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-23s\033[0m %s\n", $$1, $$2}'

install:  ## Default installation (for running tasks and local scripts)
	CMAKE_POLICY_VERSION_MINIMUM=3.5 uv sync

install-connectivity:  ## Install with connectivity dependencies (for connectivity analysis & plots) -- needs notebooks as well
	CMAKE_POLICY_VERSION_MINIMUM=3.5 uv sync --extra notebooks --extra connectivity

install-notebooks:  ## Install with notebooks dependencies (for running notebooks locally)
	CMAKE_POLICY_VERSION_MINIMUM=3.5 uv sync --extra notebooks

install-service:  ## Install with service dependencies (for running as a service)
	CMAKE_POLICY_VERSION_MINIMUM=3.5 uv sync --extra service

install-all:  ## Install all dependencies (for production/deployment)
	CMAKE_POLICY_VERSION_MINIMUM=3.5 uv sync --extra all

# ---- BlueRecording (optional, for extracellular recording) ----
# Prerequisites: brew install openmpi hdf5-mpi cmake (macOS)
#                sudo apt install openmpi-bin libopenmpi-dev libhdf5-openmpi-dev cmake ninja-build (Linux)
NEURODAMUS_MODELS_REPO := https://github.com/openbraininstitute/neurodamus-models.git
NEURODAMUS_MODELS_DIR := neurodamus-models
NEURODAMUS_NEOCORTEX_ROOT := $(CURDIR)/$(NEURODAMUS_MODELS_DIR)/build/install

install-bluerecording:  ## Install with bluerecording dependencies (for extracellular recording)
	@echo "=== Installing bluerecording dependencies ==="
	@echo "Prerequisites: openmpi, hdf5-mpi, cmake"
	@echo "  macOS:  brew install openmpi hdf5-mpi cmake"
	@echo "  Linux:  sudo apt install openmpi-bin libopenmpi-dev libhdf5-openmpi-dev cmake ninja-build"
	@echo ""
	CMAKE_POLICY_VERSION_MINIMUM=3.5 uv sync --extra bluerecording
	@echo "=== Building neurodamus-models ==="
	@if [ ! -d "$(NEURODAMUS_MODELS_DIR)" ]; then \
		git clone --depth=1 $(NEURODAMUS_MODELS_REPO); \
	fi
	NEURODAMUS_PYTHON=$$(uv run python -c "import neurodamus; from pathlib import Path; print(Path(neurodamus.__file__).parent / 'data')") && \
	uv run cmake -B $(NEURODAMUS_MODELS_DIR)/build -S $(NEURODAMUS_MODELS_DIR)/ \
		-DPython_EXECUTABLE=$$(uv run which python) \
		-DCMAKE_INSTALL_PREFIX=$(NEURODAMUS_NEOCORTEX_ROOT) \
		-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON \
		-DNEURODAMUS_CORE_DIR=$$NEURODAMUS_PYTHON \
		-DNEURODAMUS_MECHANISMS=neocortex \
		-DNEURODAMUS_NCX_V5=ON \
		-DNEURODAMUS_ENABLE_REPORTING=OFF
	cmake --build $(NEURODAMUS_MODELS_DIR)/build
	cmake --install $(NEURODAMUS_MODELS_DIR)/build
	@echo "=== Rebuilding h5py with MPI support ==="
	uv pip install cython numpy setuptools pkgconfig
	uv pip uninstall h5py
	CC=$$(which mpicc) HDF5_MPI=ON HDF5_DIR=$$(dirname "$$(dirname "$$(which h5cc)")") \
		uv pip install --no-cache --no-binary h5py h5py --no-build-isolation
	@echo "=== Generating bluerecording_env.sh ==="
	@echo '# Auto-generated by make install-bluerecording — source this to set bluerecording env vars.' > bluerecording_env.sh
	@echo '# Usage: source bluerecording_env.sh' >> bluerecording_env.sh
	@echo '#' >> bluerecording_env.sh
	@echo '# IMPORTANT: Use "source .venv/bin/activate" instead of "uv run" for bluerecording commands.' >> bluerecording_env.sh
	@echo '# "uv run" re-syncs the environment and will replace the MPI-enabled h5py with the default wheel.' >> bluerecording_env.sh
	@echo 'source "$(CURDIR)/.venv/bin/activate"' >> bluerecording_env.sh
	@echo 'export NEURODAMUS_NEOCORTEX_ROOT="$(NEURODAMUS_NEOCORTEX_ROOT)"' >> bluerecording_env.sh
	@echo 'export HOC_LIBRARY_PATH="$(NEURODAMUS_NEOCORTEX_ROOT)/share/neurodamus_neocortex/hoc"' >> bluerecording_env.sh
	@OS_NAME=$$(uname -s); \
	if [ "$$OS_NAME" = "Darwin" ]; then \
		echo 'export CORENEURONLIB="$(NEURODAMUS_NEOCORTEX_ROOT)/lib/libcorenrnmech.dylib"' >> bluerecording_env.sh; \
		echo 'export NRNMECH_LIB_PATH="$(NEURODAMUS_NEOCORTEX_ROOT)/lib/libnrnmech.dylib"' >> bluerecording_env.sh; \
	else \
		echo 'export CORENEURONLIB="$(NEURODAMUS_NEOCORTEX_ROOT)/lib/libcorenrnmech.so"' >> bluerecording_env.sh; \
		echo 'export NRNMECH_LIB_PATH="$(NEURODAMUS_NEOCORTEX_ROOT)/lib/libnrnmech.so"' >> bluerecording_env.sh; \
	fi
	@echo 'export PATH="$(NEURODAMUS_NEOCORTEX_ROOT)/bin:$$PATH"' >> bluerecording_env.sh
	@echo ""
	@echo "=== BlueRecording installation complete ==="
	@echo "To activate the environment, run:"
	@echo ""
	@echo "    source bluerecording_env.sh"
	@echo ""
	@echo "NOTE: Do not use 'uv run' for bluerecording commands — it will overwrite the MPI-enabled h5py."
	@echo "      Use 'source bluerecording_env.sh' which activates the venv directly."
	@echo ""

install-dev:  ## Install all dependencies + dev tools (for development)
	CMAKE_POLICY_VERSION_MINIMUM=3.5 uv sync --extra all --group dev

install-ipython: install ## Create a virtual environment and install the ipython kernel
	uv run python -m ipykernel install --user --name=obi-one --display-name "obi-one"

install-docs:  ## Install documentation dependencies without uninstalling other dependencies
	uv sync --group docs

serve-docs:  ## Serve documentation locally
	uv run mkdocs serve

compile-deps:  ## Create or update the lock file, without upgrading the version of the dependencies
	uv lock --upgrade-package entitysdk

upgrade-deps:  ## Create or update the lock file, using the latest version of the dependencies
	uv lock --upgrade

check-deps:  ## Check that the dependencies in the existing lock file are valid, and that entitysdk is at the latest version
	uv lock --locked --upgrade-package entitysdk

format:  ## Run formatters
	uv run -m ruff format $(FILE)
	uv run -m ruff check --fix $(FILE)

lint:  ## Run linters
	uv run -m ruff format --check
	uv run -m ruff check
	#uv run -m pyright obi_one

format_count: ## Count the number of errors by file
	uv run -m ruff check --output-format=json | jq '.[].filename' | sort | uniq -c

format_types: ## Count the number of errors by type
	uv run -m ruff check --output-format=json | jq -r '.[] | [.code, .message] | @tsv' | sort | uniq -c

build:  ## Build the Docker image
	docker compose --profile "*" --progress=plain build app

publish: build  ## Publish the Docker image to DockerHub
	docker compose push app

test-local:  ## Run tests locally
	@$(call load_env,test-local)
	uv run -m pytest
	uv run -m coverage xml
	uv run -m coverage html

test-file: ## Run tests in a single test file locally. Usage: make test-file FILE=path/to/test_file.py
	@$(call load_env,test-local)
	uv run -m pytest $(FILE) --no-cov --disable-warnings

test-schema: ## Run schema tests locally.
	@$(call load_env,test-local)
	uv run -m pytest tests/ui_schema/test_schema.py --no-cov --disable-warnings

test-schema-verbose: ## Run schema tests locally with verbose output.
	@$(call load_env,test-local)
	uv run -m pytest tests/ui_schema/test_schema.py --no-cov --disable-warnings --log-cli-level=INFO

test-docker: build  ## Run tests in Docker
	docker compose run --rm --remove-orphans test

pip-audit:  ## Run package auditing
	uv run --with pip-audit pip-audit --local --progress-spinner off --desc off \
		--ignore-vuln CVE-2025-53000

run-local: ## Run the application locally
	@$(call load_env,run-local)
	uv run -m app run --host $(UVICORN_HOST) --port $(UVICORN_PORT) --reload

run-docker: build  ## Run the application in Docker
	docker compose up app --watch --remove-orphans

destroy: export COMPOSE_PROFILES=run,test
destroy:  ## Take down the application and remove the volumes
	docker compose down --remove-orphans --volumes
