[project]
name = "obi"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "pydantic>=2.10.6",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["obi"]

[project.optional-dependencies]
subcircuit_extraction = [
    "brainbuilder"
]
#subcircuit_extraction = [
#    "brainbuilder @ file:////Users/james/Documents/obi/code/brainbuilder"
#]



connectivity = [
    "Connectome-Utilities",
    "connectome-analysis>=1.0.1"
]

fastapi_app = [
    "fastapi",
    "uvicorn",
    "starlette"
]

jupyter = [
    "jupyter", 
    "notebook", 
    "jupyterlab",
    "ipykernel"
]


database = [
    "sqlalchemy"
]



