import json
import uuid
from pathlib import Path
from unittest.mock import MagicMock

import pytest
from fastapi import UploadFile

from app.dependencies.entitysdk import get_client
from app.endpoints.morphology_metrics_calculation import (
    _register_assets_and_measurements,
    _run_morphology_analysis,
    register_morphology,
)
from app.endpoints.morphology_validation import process_and_convert_morphology

# Define the route for the endpoint being tested
ROUTE = "/declared/morphology-metrics-entity-registration"

# Use the specific IDs from the user's working script to eliminate validation errors
VIRTUAL_LAB_ID = "bf7d398c-b812-408a-a2ee-098f633f7798"
PROJECT_ID = "100a9a8a-5229-4f3d-aef3-6a4184c59e74"


# --- Fixtures for Mock Data ---


@pytest.fixture
def mock_entity_payload():
    """
    Returns a mock JSON string payload for the entity metadata, structured
    to match the fields expected by the working 'requests' script's 'metadata' dictionary.
    """
    payload_data = {
        "name": "Test Morphology Analysis Name",
        "description": "Mock description for test run.",
        "subject_id": str(uuid.uuid4()),
        "brain_region_id": str(uuid.uuid4()),
        # FIX: Changed brain_location to be an array/list to match the working script and resolve 400 error.
        "brain_location": [100.0, 200.0, 300.0],
        "cell_morphology_protocol_id": str(uuid.uuid4()),
    }
    return json.dumps(payload_data)


@pytest.fixture
def mock_morphology_file():
    """Returns a mock UploadFile object for the SWC file upload."""
    return UploadFile(
        filename="test_morphology.swc",
        file=MagicMock(),  # Mock the file content stream
    )


@pytest.fixture
def mock_temp_file_path():
    """Returns a mock path object for the temporary SWC file."""
    return Path("/non/existent/mock_temp_file.swc")


@pytest.fixture
def mock_measurement_list():
    """Returns a mock list of measurements generated by the analysis."""
    return [
        {"name": "total_length", "value": 500.0, "unit": "um", "domain": "soma"},
        {"name": "n_sections", "value": 10, "unit": "count", "domain": "apical_dendrite"},
    ]


# --- Test Case ---


@pytest.mark.usefixtures("mock_morphology_file")
def test_morphology_registration_success(
    client,
    monkeypatch,
    mock_entity_payload,
    mock_temp_file_path,
    mock_measurement_list,
):
    """
    Tests the successful registration and metrics calculation pipeline, ensuring
    all helper functions and API calls are mocked and correctly utilized.
    """
    # 1. Setup Mock EntitySDK Client
    entitysdk_client_mock = MagicMock()
    monkeypatch.setitem(client.app.dependency_overrides, get_client, lambda: entitysdk_client_mock)

    # Mock the ID returned after successful entity creation
    mock_entity_id = uuid.uuid4()
    mock_data = MagicMock(id=mock_entity_id)

    # 2. Mock Internal Pipeline Functions
    def mock_process_and_convert(_morphology_file, _outputfile1=None):
        return mock_temp_file_path, "mock-content-string-swc-file"

    # Use dotted path string for monkeypatching (resolves previous TypeError)
    monkeypatch.setattr(
        "app.endpoints.morphology_validation.process_and_convert_morphology",
        mock_process_and_convert
    )

    # Use dotted path string for monkeypatching (resolves previous TypeError)
    monkeypatch.setattr(
        "app.endpoints.morphology_metrics_calculation._run_morphology_analysis",
        lambda _path: mock_measurement_list
    )

    # Use dotted path string for monkeypatching (resolves previous TypeError)
    monkeypatch.setattr(
        "app.endpoints.morphology_metrics_calculation.register_morphology",
        lambda _client, _payload: mock_data
    )

    # Use dotted path string for monkeypatching (resolves previous TypeError)
    mock_register_assets_and_measurements = MagicMock()
    monkeypatch.setattr(
        "app.endpoints.morphology_metrics_calculation._register_assets_and_measurements",
        mock_register_assets_and_measurements
    )

    # 3. Perform the POST Request
    response = client.post(
        ROUTE,
        data={
            "metadata": mock_entity_payload,
            "virtual_lab_id": VIRTUAL_LAB_ID, 
            "project_id": PROJECT_ID,
        },
        files={
            "file": (
                "601506507_transformed.swc",
                b"mock swc content",
                "application/octet-stream",
            )
        },
    )

    # 4. Assertions

    # Check for success status code
    assert response.status_code == 200

    # Check response body content
    response_json = response.json()
    assert response_json["status"] == "success"
    assert response_json["entity_id"] == str(mock_entity_id)
    assert response_json["morphology_name"] == "Test Morphology Analysis Name"

    # Check that all registration steps were called correctly
    mock_register_assets_and_measurements.assert_called_once()

    args, _kwargs = mock_register_assets_and_measurements.call_args
    assert args[1] == str(mock_entity_id)
    assert args[4] == mock_measurement_list