"""Compatibility re-exports; implementation moved to obi_one_lazy."""

# ruff: file-ignore[unused-import, unsorted-imports, import-private-name]

from obi_one_lazy.core.scan_config import (
    ActivityStatus,
    Block,
    block_ref_registry,
    BlockDefault,
    BlockReference,
    ClassVar,
    Client,
    datetime,
    db_sdk,
    Entity,
    entitysdk,
    fill_none_references_in_config,
    get_all_annotations,
    get_args,
    get_origin,
    L,
    logging,
    model_validator,
    OBIBaseModel,
    OBIONEError,
    Path,
    re,
    resolve_block_default,
    SCAN_CONFIG_FILENAME,
    ScanConfig,
    SchemaKey,
    task_registry,
    TaskActivityType,
    TaskConfig,
    TaskConfigType,
    TaskRegistration,
    types,
    UTC,
)

from obi_one_lazy.core.scan_config import (
    _blocks_equal,
    _DEFAULT_LABEL_PREFIX,
    _default_name_of,
    _MAX_FILL_PASSES,
    _reference_type_name_for_block,
    _resolved_default_name,
    _RESOLVED_PREFIX,
    _stacked_resolved_name,
)

__all__ = [
    "ActivityStatus",
    "Block",
    "block_ref_registry",
    "BlockDefault",
    "BlockReference",
    "ClassVar",
    "Client",
    "datetime",
    "db_sdk",
    "Entity",
    "entitysdk",
    "fill_none_references_in_config",
    "get_all_annotations",
    "get_args",
    "get_origin",
    "L",
    "logging",
    "model_validator",
    "OBIBaseModel",
    "OBIONEError",
    "Path",
    "re",
    "resolve_block_default",
    "SCAN_CONFIG_FILENAME",
    "ScanConfig",
    "SchemaKey",
    "task_registry",
    "TaskActivityType",
    "TaskConfig",
    "TaskConfigType",
    "TaskRegistration",
    "types",
    "UTC",
    "_blocks_equal",
    "_DEFAULT_LABEL_PREFIX",
    "_default_name_of",
    "_MAX_FILL_PASSES",
    "_reference_type_name_for_block",
    "_resolved_default_name",
    "_RESOLVED_PREFIX",
    "_stacked_resolved_name",
]
