from __future__ import annotations

from collections import defaultdict
from typing import TYPE_CHECKING, Annotated, ClassVar

import numpy as np
from pydantic import Field, NonNegativeFloat, NonNegativeInt

from obi_one.core.schema import SchemaKey, UIElement
from obi_one.core.units import Units
from obi_one.scientific.blocks.distributions.uniform import FloatUniformDistribution
from obi_one.scientific.blocks.stimuli.spike.base import SpikeStimulus
from obi_one.scientific.library.constants import (
    _DEFAULT_STIMULUS_LENGTH_MILLISECONDS,
    _MAX_SIMULATION_LENGTH_MILLISECONDS,
)
from obi_one.scientific.unions.unions_distributions import AllDistributionsReference

if TYPE_CHECKING:
    from obi_one.scientific.blocks.distributions.base import Distribution


class SpikeTimeDistributionSpikeStimulus(SpikeStimulus):
    """Spike replay generated by sampling spike times directly from a distribution."""

    title: ClassVar[str] = "Spike-Time Distribution Spike Replay (Efferent)"

    duration: (
        Annotated[NonNegativeFloat, Field(le=_MAX_SIMULATION_LENGTH_MILLISECONDS)]
        | list[Annotated[NonNegativeFloat, Field(le=_MAX_SIMULATION_LENGTH_MILLISECONDS)]]
    ) = Field(
        default=_DEFAULT_STIMULUS_LENGTH_MILLISECONDS,
        title="Duration",
        description="Time window in milliseconds from which spike times are sampled.",
        json_schema_extra={
            SchemaKey.UI_ELEMENT: UIElement.FLOAT_PARAMETER_SWEEP,
            SchemaKey.UNITS: Units.MILLISECONDS,
        },
    )

    number_of_spikes: NonNegativeInt | list[NonNegativeInt] = Field(
        default=1,
        title="Number of Spikes",
        description="Number of spike times to sample per source neuron per timestamp.",
        json_schema_extra={
            SchemaKey.UI_ELEMENT: UIElement.INT_PARAMETER_SWEEP,
        },
    )

    distribution: AllDistributionsReference | None = Field(
        default=None,
        title="Spike Time Distribution",
        description=(
            "Distribution used to sample spike times directly in milliseconds. "
            "Default: FloatUniformDistribution(low=0.0, high=duration)."
        ),
        json_schema_extra={
            SchemaKey.UI_ELEMENT: UIElement.REFERENCE,
            SchemaKey.REFERENCE_TYPE: AllDistributionsReference.__name__,
        },
    )

    resample_each_repetition: bool = Field(
        default=True,
        title="Resample Each Repetition",
        description=(
            "When set to True, spike times are regenerated for every timestamp "
            "repetition. When False, the same relative spike-time pattern is reused "
            "for all repetitions."
        ),
        json_schema_extra={
            SchemaKey.UI_ELEMENT: UIElement.BOOLEAN_INPUT,
        },
    )

    @staticmethod
    def _sample_spike_times_from_distribution(
        distribution: Distribution,
        number_of_spikes: int,
        duration: float,
        rng: np.random.Generator | None = None,
    ) -> list[float]:
        samples = distribution.sample(number_of_spikes, rng=rng)
        return sorted(float(t) for t in samples if 0.0 <= t < duration)

    def generate_spikes_by_gid(self, source_gids: list[int]) -> dict[int, list[float]]:
        if self.distribution is None:
            distribution = FloatUniformDistribution(low=0.0, high=self.duration)
        else:
            distribution = self.distribution.block

        timestamps = self._offset_timestamps()
        random_seed = getattr(distribution, "random_seed", None)
        rng = np.random.default_rng(random_seed) if random_seed is not None else None

        spikes_by_gid: dict[int, list[float]] = defaultdict(list)

        for gid in source_gids:
            if self.resample_each_repetition:
                for timestamp in timestamps:
                    relative_spikes = self._sample_spike_times_from_distribution(
                        distribution,  # ty:ignore[invalid-argument-type]
                        number_of_spikes=self.number_of_spikes,  # ty:ignore[invalid-argument-type]
                        duration=self.duration,  # ty:ignore[invalid-argument-type]
                        rng=rng,
                    )
                    spike_offset = timestamp + self.timestamp_offset  # ty:ignore[unsupported-operator]
                    spikes_by_gid[gid].extend(spike_offset + t for t in relative_spikes)
            else:
                relative_spikes = self._sample_spike_times_from_distribution(
                    distribution,  # ty:ignore[invalid-argument-type]
                    number_of_spikes=self.number_of_spikes,  # ty:ignore[invalid-argument-type]
                    duration=self.duration,  # ty:ignore[invalid-argument-type]
                    rng=rng,
                )
                for timestamp in timestamps:
                    spike_offset = timestamp + self.timestamp_offset  # ty:ignore[unsupported-operator]
                    spikes_by_gid[gid].extend(spike_offset + t for t in relative_spikes)
        return spikes_by_gid
