"""Compatibility re-exports; implementation moved to obi_one_lazy."""

# ruff: file-ignore[unused-import, unsorted-imports, import-private-name]

from obi_one_lazy.scientific.blocks.neuron_sets.combined import (
    abc,
    ATOMIC_ALL_NEURON_SETS_REFERENCE_TYPES,
    ATOMIC_ALL_NEURON_SETS_REFERENCE_UNION,
    ATOMIC_BIOPHYSICAL_NEURON_SETS_REFERENCE_TYPES,
    ATOMIC_BIOPHYSICAL_NEURON_SETS_REFERENCE_UNION,
    ATOMIC_NON_VIRTUAL_NEURON_SETS_REFERENCE_TYPES,
    ATOMIC_NON_VIRTUAL_NEURON_SETS_REFERENCE_UNION,
    ATOMIC_POINT_NEURON_SETS_REFERENCE_TYPES,
    ATOMIC_POINT_NEURON_SETS_REFERENCE_UNION,
    ATOMIC_VIRTUAL_NEURON_SETS_REFERENCE_TYPES,
    ATOMIC_VIRTUAL_NEURON_SETS_REFERENCE_UNION,
    BiophysicalCombinedNeuronSet,
    BlockReference,
    Circuit,
    CircuitUsability,
    ClassVar,
    CombinedBaseNeuronSet,
    CombinedNeuronSet,
    Field,
    L,
    Literal,
    logging,
    MappedPropertiesGroup,
    NeuronSet,
    NeuronSetPopulationType,
    NonVirtualCombinedNeuronSet,
    np,
    PointCombinedNeuronSet,
    ReferenceTag,
    SchemaKey,
    SetOperation,
    StrEnum,
    UIElement,
    VirtualCombinedNeuronSet,
)

from obi_one_lazy.scientific.blocks.neuron_sets.combined import (
    _MAX_COMBINED_DEPTH,
    _OPERATION_MAP,
)

__all__ = [
    "abc",
    "ATOMIC_ALL_NEURON_SETS_REFERENCE_TYPES",
    "ATOMIC_ALL_NEURON_SETS_REFERENCE_UNION",
    "ATOMIC_BIOPHYSICAL_NEURON_SETS_REFERENCE_TYPES",
    "ATOMIC_BIOPHYSICAL_NEURON_SETS_REFERENCE_UNION",
    "ATOMIC_NON_VIRTUAL_NEURON_SETS_REFERENCE_TYPES",
    "ATOMIC_NON_VIRTUAL_NEURON_SETS_REFERENCE_UNION",
    "ATOMIC_POINT_NEURON_SETS_REFERENCE_TYPES",
    "ATOMIC_POINT_NEURON_SETS_REFERENCE_UNION",
    "ATOMIC_VIRTUAL_NEURON_SETS_REFERENCE_TYPES",
    "ATOMIC_VIRTUAL_NEURON_SETS_REFERENCE_UNION",
    "BiophysicalCombinedNeuronSet",
    "BlockReference",
    "Circuit",
    "CircuitUsability",
    "ClassVar",
    "CombinedBaseNeuronSet",
    "CombinedNeuronSet",
    "Field",
    "L",
    "Literal",
    "logging",
    "MappedPropertiesGroup",
    "NeuronSet",
    "NeuronSetPopulationType",
    "NonVirtualCombinedNeuronSet",
    "np",
    "PointCombinedNeuronSet",
    "ReferenceTag",
    "SchemaKey",
    "SetOperation",
    "StrEnum",
    "UIElement",
    "VirtualCombinedNeuronSet",
    "_MAX_COMBINED_DEPTH",
    "_OPERATION_MAP",
]
