PROPERTY_NEURON_SET_TITLE_PREFIX = "BY NODE PROPERTY "
PREDEFINED_NEURON_SET_TITLE_PREFIX = "PREDEFINED "
ID_NEURON_SET_TITLE_PREFIX = "BY ID "
POPULATION_NEURON_SET_TITLE_PREFIX = "SAMPLE POPULATION "

BIOPHYSICAL_NEURON_SET_TITLE_SUFFIX = "(Biophysical)"
VIRTUAL_NEURON_SET_TITLE_SUFFIX = "(Virtual)"
POINT_NEURON_SET_TITLE_SUFFIX = "(Point)"
