"""Compatibility re-exports; implementation moved to obi_one_lazy."""

# ruff: file-ignore[unused-import, unsorted-imports]

from obi_one_lazy.scientific.blocks.neuron_sets.constants import (
    ALL_NEURON_SET_TITLE_PREFIX,
    ALL_POPULATION_TYPES_NEURON_SET_TITLE_SUFFIX,
    BIOPHYSICAL_NEURON_SET_TITLE_SUFFIX,
    ID_NEURON_SET_TITLE_PREFIX,
    MULTI_POPULATION_NEURON_SET_TITLE_SUFFIX,
    POINT_NEURON_SET_TITLE_SUFFIX,
    POPULATION_NEURON_SET_TITLE_PREFIX,
    PREDEFINED_NEURON_SET_TITLE_PREFIX,
    PROPERTY_NEURON_SET_TITLE_PREFIX,
    VIRTUAL_NEURON_SET_TITLE_SUFFIX,
)

__all__ = [
    "ALL_NEURON_SET_TITLE_PREFIX",
    "ALL_POPULATION_TYPES_NEURON_SET_TITLE_SUFFIX",
    "BIOPHYSICAL_NEURON_SET_TITLE_SUFFIX",
    "ID_NEURON_SET_TITLE_PREFIX",
    "MULTI_POPULATION_NEURON_SET_TITLE_SUFFIX",
    "POINT_NEURON_SET_TITLE_SUFFIX",
    "POPULATION_NEURON_SET_TITLE_PREFIX",
    "PREDEFINED_NEURON_SET_TITLE_PREFIX",
    "PROPERTY_NEURON_SET_TITLE_PREFIX",
    "VIRTUAL_NEURON_SET_TITLE_SUFFIX",
]
