"""Compatibility re-exports; implementation moved to obi_one_lazy."""

# ruff: file-ignore[unused-import, unsorted-imports]

from obi_one_lazy.scientific.blocks.neuron_sets.deprecated import (
    abc,
    AllNeurons,
    Annotated,
    Circuit,
    CircuitMappedProperties,
    CircuitUsability,
    ClassVar,
    ConfigValidationError,
    DeprecatedNeuronSet,
    DeprecatedSampleNeuronSet,
    ExcitatoryNeurons,
    Field,
    IDNeuronSet,
    InhibitoryNeurons,
    MappedPropertiesGroup,
    NamedTuple,
    nbS1POmInputs,
    nbS1VPMInputs,
    NeuronSet,
    NeuronSetPopulationType,
    NodeSetType,
    NonNegativeFloat,
    PredefinedNeuronSet,
    rCA1CA3Inputs,
    SchemaKey,
    UIElement,
    Units,
)

__all__ = [
    "abc",
    "AllNeurons",
    "Annotated",
    "Circuit",
    "CircuitMappedProperties",
    "CircuitUsability",
    "ClassVar",
    "ConfigValidationError",
    "DeprecatedNeuronSet",
    "DeprecatedSampleNeuronSet",
    "ExcitatoryNeurons",
    "Field",
    "IDNeuronSet",
    "InhibitoryNeurons",
    "MappedPropertiesGroup",
    "NamedTuple",
    "nbS1POmInputs",
    "nbS1VPMInputs",
    "NeuronSet",
    "NeuronSetPopulationType",
    "NodeSetType",
    "NonNegativeFloat",
    "PredefinedNeuronSet",
    "rCA1CA3Inputs",
    "SchemaKey",
    "UIElement",
    "Units",
]
