"""Compatibility re-exports; implementation moved to obi_one_lazy."""

# ruff: file-ignore[unused-import, unsorted-imports]

from obi_one_lazy.scientific.blocks.neuron_sets.id import (
    abc,
    Annotated,
    BIOPHYSICAL_NEURON_SET_TITLE_SUFFIX,
    BiophysicalPopulationIDNeuronSet,
    BiophysicalPopulationNeuronSetMixin,
    Circuit,
    ClassVar,
    Field,
    ID_NEURON_SET_TITLE_PREFIX,
    IDPopulationBaseNeuronSet,
    L,
    logging,
    NamedTuple,
    POINT_NEURON_SET_TITLE_SUFFIX,
    PointPopulationIDNeuronSet,
    PointPopulationNeuronSetMixin,
    PopulationBaseNeuronSet,
    SchemaKey,
    UIElement,
    VIRTUAL_NEURON_SET_TITLE_SUFFIX,
    VirtualPopulationIDNeuronSet,
    VirtualPopulationNeuronSetMixin,
)

__all__ = [
    "abc",
    "Annotated",
    "BIOPHYSICAL_NEURON_SET_TITLE_SUFFIX",
    "BiophysicalPopulationIDNeuronSet",
    "BiophysicalPopulationNeuronSetMixin",
    "Circuit",
    "ClassVar",
    "Field",
    "ID_NEURON_SET_TITLE_PREFIX",
    "IDPopulationBaseNeuronSet",
    "L",
    "logging",
    "NamedTuple",
    "POINT_NEURON_SET_TITLE_SUFFIX",
    "PointPopulationIDNeuronSet",
    "PointPopulationNeuronSetMixin",
    "PopulationBaseNeuronSet",
    "SchemaKey",
    "UIElement",
    "VIRTUAL_NEURON_SET_TITLE_SUFFIX",
    "VirtualPopulationIDNeuronSet",
    "VirtualPopulationNeuronSetMixin",
]
