"""Compatibility re-exports; implementation moved to obi_one_lazy."""

# ruff: file-ignore[unused-import, unsorted-imports, import-private-name]

from obi_one_lazy.scientific.blocks.neuron_sets.predefined import (
    abc,
    Annotated,
    BIOPHYSICAL_NEURON_SET_TITLE_SUFFIX,
    BiophysicalPopulationNeuronSetMixin,
    BiophysicalPopulationPredefinedNeuronSet,
    Circuit,
    CircuitMappedProperties,
    CircuitNode,
    ClassVar,
    Field,
    L,
    logging,
    MappedPropertiesGroup,
    MAX_SAMPLE_PERCENTAGE,
    MULTI_POPULATION_NEURON_SET_TITLE_SUFFIX,
    MultiPopulationPredefinedNeuronSet,
    NeuronSet,
    NeuronSetPopulationType,
    NodeSetType,
    POINT_NEURON_SET_TITLE_SUFFIX,
    PointPopulationNeuronSetMixin,
    PointPopulationPredefinedNeuronSet,
    PopulationBaseNeuronSet,
    PREDEFINED_NEURON_SET_TITLE_PREFIX,
    PredefinedBaseNeuronSet,
    PredefinedPopulationBaseNeuronSet,
    SchemaKey,
    snap,
    UIElement,
    VIRTUAL_NEURON_SET_TITLE_SUFFIX,
    VirtualPopulationNeuronSetMixin,
    VirtualPopulationPredefinedNeuronSet,
)

from obi_one_lazy.scientific.blocks.neuron_sets.predefined import (
    _flatten_node_set,
    _MAX_FLATTEN_DEPTH,
    _pin_to_population,
)

__all__ = [
    "abc",
    "Annotated",
    "BIOPHYSICAL_NEURON_SET_TITLE_SUFFIX",
    "BiophysicalPopulationNeuronSetMixin",
    "BiophysicalPopulationPredefinedNeuronSet",
    "Circuit",
    "CircuitMappedProperties",
    "CircuitNode",
    "ClassVar",
    "Field",
    "L",
    "logging",
    "MappedPropertiesGroup",
    "MAX_SAMPLE_PERCENTAGE",
    "MULTI_POPULATION_NEURON_SET_TITLE_SUFFIX",
    "MultiPopulationPredefinedNeuronSet",
    "NeuronSet",
    "NeuronSetPopulationType",
    "NodeSetType",
    "POINT_NEURON_SET_TITLE_SUFFIX",
    "PointPopulationNeuronSetMixin",
    "PointPopulationPredefinedNeuronSet",
    "PopulationBaseNeuronSet",
    "PREDEFINED_NEURON_SET_TITLE_PREFIX",
    "PredefinedBaseNeuronSet",
    "PredefinedPopulationBaseNeuronSet",
    "SchemaKey",
    "snap",
    "UIElement",
    "VIRTUAL_NEURON_SET_TITLE_SUFFIX",
    "VirtualPopulationNeuronSetMixin",
    "VirtualPopulationPredefinedNeuronSet",
    "_flatten_node_set",
    "_MAX_FLATTEN_DEPTH",
    "_pin_to_population",
]
