"""Catalogue of bluepyefe protocols and eFEL features as Pydantic models.

Replaces the flat ``EFEATURE_CATALOGUE_BY_PROTOCOL`` dict-of-strings: each
feature is a Pydantic subclass of :class:`EFeature` carrying its own tunable
parameters (in :mod:`.efeatures`), and each protocol is a subclass of
:class:`Protocol` declaring which features it can extract (in
:mod:`.protocols`).
"""

from obi_one.scientific.tasks.emodel_optimization._01_efeature_extraction.protocols_and_features.efeatures import (
    AdaptationIndex,
    AHPDepth,
    AHPTimeFromPeak,
    AP1Amp,
    APAmplitude,
    APBeginVoltage,
    APBeginWidth,
    APDurationHalfWidth,
    DecayTimeConstantAfterStim,
    DepolBlockBool,
    DoubletISI,
    EFeature,
    InvFirstISI,
    InvLastISI,
    InvSecondISI,
    InvThirdISI,
    InvTimeToFirstSpike,
    IrregularityIndex,
    ISICV,
    ISILogSlope,
    MeanFrequency,
    MinAHPValues,
    NumberInitialSpikes,
    OhmicInputResistanceVbSsse,
    SagAmplitude,
    SagRatio1,
    SagRatio2,
    Spikecount,
    StrictBurstMeanFreq,
    StrictBurstNumber,
    TimeToFirstSpike,
    TimeToLastSpike,
    VoltageAfterStim,
    VoltageBase,
)
from obi_one.scientific.tasks.emodel_optimization._01_efeature_extraction.protocols_and_features.protocols import (
    APWaveform,
    IDhyperpol,
    IDrest,
    IDthresh,
    IV,
    PROTOCOL_CATALOGUE,
    Protocol,
    ProtocolUnion,
    SAHP,
    available_features_by_protocol_name,
)

__all__ = [
    "PROTOCOL_CATALOGUE",
    "APWaveform",
    "AHPDepth",
    "AHPTimeFromPeak",
    "AP1Amp",
    "APAmplitude",
    "APBeginVoltage",
    "APBeginWidth",
    "APDurationHalfWidth",
    "AdaptationIndex",
    "DecayTimeConstantAfterStim",
    "DepolBlockBool",
    "DoubletISI",
    "EFeature",
    "ISICV",
    "ISILogSlope",
    "IDhyperpol",
    "IDrest",
    "IDthresh",
    "IV",
    "InvFirstISI",
    "InvLastISI",
    "InvSecondISI",
    "InvThirdISI",
    "InvTimeToFirstSpike",
    "IrregularityIndex",
    "MeanFrequency",
    "MinAHPValues",
    "NumberInitialSpikes",
    "OhmicInputResistanceVbSsse",
    "Protocol",
    "ProtocolUnion",
    "SAHP",
    "SagAmplitude",
    "SagRatio1",
    "SagRatio2",
    "Spikecount",
    "StrictBurstMeanFreq",
    "StrictBurstNumber",
    "TimeToFirstSpike",
    "TimeToLastSpike",
    "VoltageAfterStim",
    "VoltageBase",
    "available_features_by_protocol_name",
]
