"""Configuration for running NEST simulations from SONATA configs."""

from typing import ClassVar

from pydantic import Field

from obi_one.core.block import Block
from obi_one.core.path import NamedPath
from obi_one.core.schema import SchemaKey, UIElement
from obi_one.core.single import SingleConfigMixin
from obi_one.scientific.library.info_scan_config.config import InfoScanConfig


class NestSimulationFromSonataScanConfig(InfoScanConfig):
    """Configuration for running a NEST simulation from SONATA config files.

    Takes the output of generate-simulations (simulation_config.json) and
    executes the simulation using the NEST simulator with point neuron models.
    """

    name: ClassVar[str] = "NEST Simulation from SONATA"
    description: ClassVar[str] = (
        "Run a NEST simulation from SONATA config files generated by generate-simulations"
    )
    single_coord_class_name: ClassVar[str] = "NestSimulationFromSonataSingleConfig"

    class Initialize(Block):
        """Initialization parameters for NEST simulation."""

        simulation_config_path: NamedPath | list[NamedPath] = Field(
            title="Simulation Config Path",
            description="Path to the SONATA simulation_config.json file "
            "generated by generate-simulations.",
            json_schema_extra={
                # SchemaKey.UI_ELEMENT: UIElement.PATH,
            },
        )

        nest_model: str | list[str] = Field(
            default="iaf_psc_alpha",
            title="NEST Neuron Model",
            description="NEST point neuron model to use for all biophysical populations. "
            "Examples: 'iaf_psc_alpha', 'iaf_psc_exp', 'iaf_cond_alpha', 'aeif_cond_exp'.",
            json_schema_extra={
                # SchemaKey.UI_ELEMENT: UIElement.STRING_PARAMETER_SWEEP,
            },
        )

    initialize: Initialize = Field(
        title="Initialize",
        description="Initialization parameters for the NEST simulation.",
        json_schema_extra={
            SchemaKey.UI_ELEMENT: UIElement.BLOCK_SINGLE,
        },
    )


class NestSimulationFromSonataSingleConfig(NestSimulationFromSonataScanConfig, SingleConfigMixin):
    """Single-coordinate configuration for a NEST simulation from SONATA."""
