"""Task to run a NEST simulation from SONATA config files.

Reads SONATA ``simulation_config.json`` (generated by generate-simulations),
builds a NEST point-neuron network from the referenced SONATA circuit, applies
stimuli / recordings / manipulations through the mirrored nest_blocks handlers,
and writes SONATA-compatible output files.
"""

import json
import logging
from pathlib import Path
from typing import Any, ClassVar

import h5py
import numpy as np
from pydantic import PrivateAttr

from obi_one.core.task import Task
from obi_one.scientific.tasks.nest_simulation_from_sonata.config import (
    NestSimulationFromSonataSingleConfig,
)
from obi_one.scientific.tasks.nest_simulation_from_sonata.nest_blocks.base import (
    NestFeatureNotSupportedError,
)
from obi_one.scientific.tasks.nest_simulation_from_sonata.nest_blocks.manipulations import (
    get_connection_override_handler,
    get_modification_handler,
)
from obi_one.scientific.tasks.nest_simulation_from_sonata.nest_blocks.recordings import (
    NestSpikeRecording,
    get_report_handler,
)
from obi_one.scientific.tasks.nest_simulation_from_sonata.nest_blocks.stimuli import (
    get_input_handler,
)

L = logging.getLogger(__name__)

_OUTPUT_DIR = "nest_output"
_SPIKES_FILE = "spikes.h5"
_VOLTAGE_FILE = "voltage.h5"


class NestSimulationFromSonataTask(Task):
    """Execute a NEST simulation from a SONATA simulation config.

    Reads the SONATA ``simulation_config.json`` produced by the
    ``GenerateSimulationTask``, builds a NEST network using point-neuron
    models, applies stimuli and recordings via the mirrored handler classes,
    runs the simulation, and saves output in SONATA-compatible format.
    """

    config: NestSimulationFromSonataSingleConfig

    SPIKES_FILE_NAME: ClassVar[str] = _SPIKES_FILE
    VOLTAGE_FILE_NAME: ClassVar[str] = _VOLTAGE_FILE

    _sonata_config: dict = PrivateAttr(default_factory=dict)
    _circuit_config: dict = PrivateAttr(default_factory=dict)
    _node_sets: dict = PrivateAttr(default_factory=dict)
    _node_collections: dict[str, Any] = PrivateAttr(default_factory=dict)
    _population_types: dict[str, str] = PrivateAttr(default_factory=dict)
    _recording_devices: dict[str, Any] = PrivateAttr(default_factory=dict)

    def execute(
        self,
        *,
        db_client: Any = None,  # noqa: ARG002
        entity_cache: bool = False,  # noqa: ARG002
        execution_activity_id: str | None = None,  # noqa: ARG002
    ) -> None:
        """Run the NEST simulation.

        Steps:
            1. Load and parse SONATA config files.
            2. Initialise the NEST kernel.
            3. Build the network (neurons + connections) from SONATA circuit.
            4. Apply SONATA ``conditions`` (where supported).
            5. Apply SONATA ``inputs`` via stimulus handlers.
            6. Create SONATA ``reports`` via recording handlers.
            7. Warn about unsupported ``connection_overrides`` / ``modifications``.
            8. Simulate.
            9. Write SONATA-compatible output files.
        """
        try:
            import nest  # noqa: PLC0415
        except ImportError as e:
            msg = (
                "The 'nest' package is required to run NEST simulations. "
                "Install it with: pip install nest-simulator"
            )
            raise ImportError(msg) from e

        sim_config_path = Path(self.config.initialize.simulation_config_path.path).resolve()
        output_dir = Path(self.config.coordinate_output_root) / _OUTPUT_DIR
        output_dir.mkdir(parents=True, exist_ok=True)

        self._load_configs(sim_config_path)

        nest.ResetKernel()
        self._configure_nest_kernel(nest)

        self._build_network(nest)
        self._apply_conditions()
        self._apply_inputs(nest, sim_config_path.parent)
        self._apply_reports(nest)
        self._warn_connection_overrides()
        self._warn_modifications()

        tstop = self._sonata_config.get("run", {}).get(
            "tstop",
            self._sonata_config.get("run", {}).get("duration", 1000.0),
        )
        L.info("Starting NEST simulation for %.1f ms", tstop)
        nest.Simulate(tstop)
        L.info("NEST simulation completed")

        self._write_output(output_dir)

    def _load_configs(self, sim_config_path: Path) -> None:
        """Load simulation_config.json, circuit_config.json, and node_sets.json."""
        with sim_config_path.open(encoding="utf-8") as f:
            self._sonata_config = json.load(f)

        network_path = self._sonata_config.get("network")
        if network_path:
            circuit_path = (sim_config_path.parent / network_path).resolve()
            with circuit_path.open(encoding="utf-8") as f:
                self._circuit_config = json.load(f)
            self._resolve_circuit_paths(circuit_path.parent)
        elif "networks" in self._sonata_config:
            self._circuit_config = self._sonata_config
            self._resolve_circuit_paths(sim_config_path.parent)
        else:
            L.warning("No 'network' field in simulation config; circuit will not be loaded.")

        node_sets_file = self._sonata_config.get("node_sets_file")
        if node_sets_file:
            ns_path = (sim_config_path.parent / node_sets_file).resolve()
            if ns_path.exists():
                with ns_path.open(encoding="utf-8") as f:
                    self._node_sets = json.load(f)

    def _resolve_circuit_paths(self, base_dir: Path) -> None:
        """Resolve ``$BASE_DIR`` and other manifest variables to absolute paths."""
        manifest = self._circuit_config.get("manifest", {})
        resolved = {}
        for key, raw_value in manifest.items():
            k = key.lstrip("$")
            val = str(raw_value)
            if "$BASE_DIR" in val:
                val = val.replace("$BASE_DIR", ".")
            resolved[k] = str((base_dir / val).resolve())

        def _substitute(obj: Any) -> Any:
            if isinstance(obj, dict):
                return {k: _substitute(v) for k, v in obj.items()}
            if isinstance(obj, list):
                return [_substitute(e) for e in obj]
            if isinstance(obj, str) and "$" in obj:
                result = obj
                for var, path in resolved.items():
                    result = result.replace(f"${var}", path)
                return result
            return obj

        self._circuit_config = _substitute(self._circuit_config)

    def _configure_nest_kernel(self, nest: Any) -> None:
        """Set NEST kernel parameters from the SONATA run section."""
        run = self._sonata_config.get("run", {})
        dt = run.get("dt", 0.025)
        nest.SetKernelStatus({"resolution": dt})

        rng_seed = run.get("random_seed", 1)
        nest.SetKernelStatus({"rng_seed": rng_seed})

    def _build_network(self, nest: Any) -> None:
        """Build the NEST network from SONATA circuit HDF5 files.

        Biophysical populations are created as point neurons with the model
        specified in the config. Virtual populations are created as
        ``spike_generator`` devices.
        """
        default_nest_model = self.config.initialize.nest_model
        nodes_confs = self._circuit_config.get("networks", {}).get("nodes", [])

        for nodes_conf in nodes_confs:
            nodes_file = nodes_conf.get("nodes_file", "")
            populations = nodes_conf.get("populations", {})

            if not populations:
                populations = self._discover_populations_from_hdf5(
                    nodes_file, nodes_conf.get("node_types_file")
                )

            for pop_name, pop_info in populations.items():
                pop_type = pop_info.get("type", "biophysical")
                self._population_types[pop_name] = pop_type

                nest_model, n_nodes, dynamics_params = self._read_node_model_params(
                    nodes_file, pop_name, default_nest_model,
                )

                if pop_type == "virtual":
                    self._node_collections[pop_name] = self._create_virtual_population(
                        nest, pop_name, n_nodes
                    )
                else:
                    self._node_collections[pop_name] = nest.Create(nest_model, n=n_nodes)
                    if dynamics_params:
                        self._node_collections[pop_name].set(**dynamics_params)

                L.info(
                    "Created %d NEST neurons for population '%s' (type=%s, model=%s)",
                    n_nodes,
                    pop_name,
                    pop_type,
                    nest_model if pop_type != "virtual" else "spike_generator",
                )

        self._connect_edges(nest)

    @staticmethod
    def _read_node_model_params(
        nodes_file: str, pop_name: str, default_model: str,
    ) -> tuple[str, int, dict[str, Any]]:
        """Read neuron model and dynamics parameters from the SONATA nodes HDF5.

        Looks for ``0/model_template`` (string) to determine the NEST model and
        ``0/dynamics_params/*`` (scalar or per-neuron datasets) for neuron
        parameters.  Falls back to *default_model* with no dynamics parameters
        when these fields are absent.

        Returns:
            Tuple of ``(nest_model, n_nodes, dynamics_params)``.
        """
        nest_model = default_model
        dynamics_params: dict[str, Any] = {}

        with h5py.File(nodes_file, "r") as f:
            pop_grp = f["nodes"][pop_name]
            n_nodes = int(pop_grp["node_type_id"].shape[0])

            if "0" in pop_grp:
                grp = pop_grp["0"]
                if "model_template" in grp:
                    raw = grp["model_template"][()]
                    nest_model = raw.decode("utf-8") if isinstance(raw, bytes) else str(raw)

                if "dynamics_params" in grp:
                    for param_name in grp["dynamics_params"]:
                        val = grp["dynamics_params"][param_name][()]
                        if isinstance(val, np.ndarray) and val.size == 1:
                            dynamics_params[param_name] = float(val.item())
                        elif isinstance(val, np.ndarray):
                            dynamics_params[param_name] = val.tolist()
                        else:
                            dynamics_params[param_name] = float(val)

        if dynamics_params:
            L.info(
                "Population '%s': model_template='%s', dynamics_params=%s",
                pop_name,
                nest_model,
                list(dynamics_params.keys()),
            )

        return nest_model, n_nodes, dynamics_params

    def _create_virtual_population(self, nest: Any, pop_name: str, n_nodes: int) -> Any:
        """Create spike_generator devices for a virtual population.

        Loads spike times from the input files referenced in the SONATA config.
        """
        inputs = self._sonata_config.get("inputs", {})
        spike_file = None
        for input_conf in inputs.values():
            if input_conf.get("node_set") == pop_name:
                spike_file = input_conf.get("spike_file")
                break

        if spike_file is None:
            return nest.Create("parrot_neuron", n=n_nodes)

        spike_path = Path(spike_file)
        if not spike_path.is_absolute():
            sim_path = Path(self.config.initialize.simulation_config_path.path).resolve()
            spike_path = (sim_path.parent / spike_file).resolve()

        if not spike_path.exists():
            L.warning(
                "Spike file '%s' for virtual population '%s' not found. "
                "Creating parrot neurons instead.",
                spike_path,
                pop_name,
            )
            return nest.Create("parrot_neuron", n=n_nodes)

        params_list = self._load_virtual_spike_params(spike_path, pop_name, n_nodes)
        if params_list is None:
            return nest.Create("parrot_neuron", n=n_nodes)
        return nest.Create("spike_generator", n=n_nodes, params=params_list)

    @staticmethod
    def _discover_populations_from_hdf5(
        nodes_file: str, node_types_file: str | None = None
    ) -> dict[str, dict]:
        """Discover population names and types from HDF5 + optional CSV."""
        import csv  # noqa: PLC0415

        populations: dict[str, dict] = {}
        with h5py.File(nodes_file, "r") as f:
            for pop_name in f["nodes"]:
                populations[pop_name] = {"type": "biophysical"}

        if node_types_file and Path(node_types_file).exists():
            with Path(node_types_file).open(encoding="utf-8") as csvf:
                reader = csv.DictReader(csvf, delimiter=" ")
                for row in reader:
                    model_type = row.get("model_type", "")
                    pop = row.get("population", "")
                    if pop in populations:
                        if model_type == "virtual":
                            populations[pop]["type"] = "virtual"
                        elif model_type in {"point_neuron", "point_process"}:
                            populations[pop]["type"] = "point_process"
                    break

        return populations

    @staticmethod
    def _load_virtual_spike_params(
        spike_path: Path, pop_name: str, n_nodes: int
    ) -> list[dict] | None:
        """Load per-node spike times from an HDF5 spike file."""
        with h5py.File(spike_path, "r") as f:
            spikes_grp = f.get("spikes", f)
            pop_grp = spikes_grp.get(pop_name, spikes_grp)

            if "node_ids" in pop_grp:
                node_ids = pop_grp["node_ids"][:]
            elif "gids" in pop_grp:
                node_ids = pop_grp["gids"][:]
            else:
                return None

            timestamps = pop_grp["timestamps"][:]

        return [
            {
                "spike_times": sorted(timestamps[node_ids == nid].tolist()),
                "allow_offgrid_times": True,
            }
            for nid in range(n_nodes)
        ]

    def _connect_edges(self, nest: Any) -> None:
        """Create NEST connections from SONATA edge HDF5 files."""
        edges_confs = self._circuit_config.get("networks", {}).get("edges", [])

        for edges_conf in edges_confs:
            edges_file = edges_conf.get("edges_file", "")
            populations = edges_conf.get("populations", {})

            for edge_pop_name in populations:
                self._connect_single_edge_population(nest, edges_file, edge_pop_name)

    def _connect_single_edge_population(
        self, nest: Any, edges_file: str, edge_pop_name: str
    ) -> None:
        """Connect a single edge population from an HDF5 file."""
        source_pop, target_pop = self._parse_edge_population_names(edge_pop_name)

        if source_pop not in self._node_collections:
            L.warning(
                "Source population '%s' not found for edge '%s'; skipping.",
                source_pop,
                edge_pop_name,
            )
            return
        if target_pop not in self._node_collections:
            L.warning(
                "Target population '%s' not found for edge '%s'; skipping.",
                target_pop,
                edge_pop_name,
            )
            return

        source_nc = self._node_collections[source_pop]
        target_nc = self._node_collections[target_pop]

        src_global = np.array(source_nc.global_id)
        tgt_global = np.array(target_nc.global_id)

        with h5py.File(edges_file, "r") as f:
            edge_grp = f["edges"][edge_pop_name]
            source_ids = edge_grp["source_node_id"][:]
            target_ids = edge_grp["target_node_id"][:]

            delays = None
            weights = None
            if "0" in edge_grp and "delay" in edge_grp["0"]:
                delays = edge_grp["0"]["delay"][:]
            if "0" in edge_grp and "conductance" in edge_grp["0"]:
                weights = edge_grp["0"]["conductance"][:]

        n_edges = len(source_ids)
        src_nest_ids = src_global[source_ids].tolist()
        tgt_nest_ids = tgt_global[target_ids].tolist()

        syn_spec: dict[str, Any] = {"synapse_model": "static_synapse"}
        if weights is not None:
            syn_spec["weight"] = weights.tolist()
        if delays is not None:
            syn_spec["delay"] = np.clip(delays, 0.1, None).tolist()

        nest.Connect(
            src_nest_ids,
            tgt_nest_ids,
            conn_spec="one_to_one",
            syn_spec=syn_spec,
        )

        L.info("Connected %d edges: %s -> %s", n_edges, source_pop, target_pop)

    def _parse_edge_population_names(self, edge_pop_name: str) -> tuple[str, str]:
        """Extract source and target population names from edge population name.

        Supports BlueBrain convention (``source__target__type``),
        BMTK convention (``source_to_target``), and falls back to matching
        known population names in the edge name.
        """
        if "__" in edge_pop_name:
            parts = edge_pop_name.split("__")
            if len(parts) >= 2:  # noqa: PLR2004
                return parts[0], parts[1]

        if "_to_" in edge_pop_name:
            src, tgt = edge_pop_name.split("_to_", maxsplit=1)
            return src, tgt

        known_pops = list(self._node_collections.keys())
        for src in known_pops:
            for tgt in known_pops:
                if edge_pop_name.startswith(src) and edge_pop_name.endswith(tgt):
                    return src, tgt

        return edge_pop_name, edge_pop_name

    def _apply_conditions(self) -> None:
        """Apply SONATA conditions to NEST neurons where possible."""
        conditions = self._sonata_config.get("conditions", {})

        v_init = conditions.get("v_init")
        if v_init is not None:
            for pop_name, nc in self._node_collections.items():
                if self._population_types.get(pop_name) != "virtual":
                    try:
                        nc.set(V_m=float(v_init))
                    except Exception:  # noqa: BLE001
                        L.warning(
                            "Could not set V_m=%.1f on population '%s'.",
                            v_init,
                            pop_name,
                        )

        for key in ("extracellular_calcium", "spike_location", "mechanisms"):
            if key in conditions:
                L.info(
                    "SONATA condition '%s' is NEURON-specific and ignored in NEST.",
                    key,
                )

    def _apply_inputs(self, nest: Any, config_dir: Path) -> None:
        """Apply each SONATA inputs entry via the appropriate handler.

        Inputs whose ``node_set`` matches a virtual population are skipped
        because their spike data was already loaded during network building.
        """
        inputs = self._sonata_config.get("inputs", {})
        virtual_pops = {
            name for name, ptype in self._population_types.items() if ptype == "virtual"
        }

        for input_name, input_config in inputs.items():
            node_set = input_config.get("node_set", "")
            if node_set in virtual_pops:
                L.info(
                    "Input '%s' targets virtual population '%s'; "
                    "spikes already loaded during network build.",
                    input_name,
                    node_set,
                )
                continue

            module = input_config.get("module", "")

            if module == "synapse_replay":
                spike_file = input_config.get("spike_file")
                if spike_file:
                    spike_path = Path(spike_file)
                    if not spike_path.is_absolute():
                        spike_path = (config_dir / spike_file).resolve()
                    resolved_config = {**input_config, "spike_file": str(spike_path)}
                else:
                    resolved_config = input_config
            else:
                resolved_config = input_config

            try:
                handler = get_input_handler(resolved_config)
                handler.apply(
                    input_name,
                    resolved_config,
                    self._node_collections,
                    self._node_sets,
                    nest,
                )
                L.info("Applied input '%s' (module=%s)", input_name, module)
            except NestFeatureNotSupportedError:
                L.warning(
                    "Input '%s' (module=%s) is not supported in NEST; skipping.",
                    input_name,
                    module,
                )

    def _apply_reports(self, nest: Any) -> None:
        """Apply each SONATA reports entry via the appropriate handler."""
        reports = self._sonata_config.get("reports", {})

        for report_name, report_config in reports.items():
            try:
                handler = get_report_handler(report_config)
                device = handler.apply(
                    report_name,
                    report_config,
                    self._node_collections,
                    self._node_sets,
                    nest,
                )
                self._recording_devices[report_name] = device
                L.info("Applied report '%s'", report_name)
            except NestFeatureNotSupportedError:
                L.warning(
                    "Report '%s' is not supported in NEST; skipping.",
                    report_name,
                )

        spike_handler = NestSpikeRecording()
        sr = spike_handler.apply(
            "spikes",
            {},
            self._node_collections,
            self._node_sets,
            nest,
        )
        self._recording_devices["spikes"] = sr

    def _warn_connection_overrides(self) -> None:
        """Log warnings for any SONATA connection_overrides entries."""
        overrides = self._sonata_config.get("connection_overrides", [])
        for override in overrides:
            name = override.get("name", "unnamed")
            try:
                handler = get_connection_override_handler(override)
                handler.apply(override, self._node_collections, self._node_sets, None)
            except NestFeatureNotSupportedError:
                L.warning(
                    "Connection override '%s' is not supported in NEST; skipping.",
                    name,
                )

    def _warn_modifications(self) -> None:
        """Log warnings for any SONATA conditions.modifications entries."""
        conditions = self._sonata_config.get("conditions", {})
        modifications = conditions.get("modifications", [])
        for mod in modifications:
            name = mod.get("name", "unnamed")
            try:
                handler = get_modification_handler(mod)
                handler.apply(mod, self._node_collections, self._node_sets, None)
            except NestFeatureNotSupportedError:
                L.warning(
                    "Modification '%s' is not supported in NEST; skipping.",
                    name,
                )

        mechanisms = conditions.get("mechanisms", {})
        if mechanisms:
            L.info(
                "SONATA conditions.mechanisms (%d entries) are NEURON-specific "
                "and ignored in NEST.",
                len(mechanisms),
            )

    def _write_output(self, output_dir: Path) -> None:
        """Write simulation results in SONATA-compatible format."""
        self._write_spike_output(output_dir)
        self._write_voltage_output(output_dir)

    def _write_spike_output(self, output_dir: Path) -> None:
        """Write spike output to SONATA HDF5."""
        sr = self._recording_devices.get("spikes")
        if sr is None:
            return

        events = sr.get("events")
        senders = events["senders"]
        times = events["times"]

        spike_file = output_dir / _SPIKES_FILE
        with h5py.File(spike_file, "w") as f:
            for pop_name, nc in self._node_collections.items():
                if self._population_types.get(pop_name) == "virtual":
                    continue

                nest_ids = np.asarray(nc.global_id, dtype=np.int64)
                if nest_ids.ndim == 0:
                    nest_ids = nest_ids.reshape(1)
                min_id = int(nest_ids.min()) if nest_ids.size > 0 else 0

                mask = np.isin(senders, nest_ids)
                pop_senders = senders[mask]
                pop_times = times[mask]

                sort_idx = np.argsort(pop_times)
                pop_senders = pop_senders[sort_idx]
                pop_times = pop_times[sort_idx]

                sonata_ids = pop_senders - min_id

                grp = f.create_group(f"spikes/{pop_name}")
                grp.create_dataset("timestamps", data=pop_times.astype(np.float64))
                grp.create_dataset("node_ids", data=sonata_ids.astype(np.uint64))
                grp["timestamps"].attrs["units"] = "ms"

        L.info("Spike output written to %s", spike_file)

    def _write_voltage_output(self, output_dir: Path) -> None:
        """Write voltage recording output to SONATA HDF5."""
        voltage_devices = {
            name: dev for name, dev in self._recording_devices.items() if name != "spikes"
        }

        if not voltage_devices:
            return

        voltage_file = output_dir / _VOLTAGE_FILE
        with h5py.File(voltage_file, "w") as f:
            for report_name, vm_device in voltage_devices.items():
                events = vm_device.get("events")
                senders = events["senders"]
                times = events["times"]
                voltages = events["V_m"]

                grp = f.create_group(f"reports/{report_name}")
                grp.create_dataset("senders", data=senders.astype(np.uint64))
                grp.create_dataset("timestamps", data=times.astype(np.float64))
                grp.create_dataset("data", data=voltages.astype(np.float64))
                grp["timestamps"].attrs["units"] = "ms"
                grp["data"].attrs["units"] = "mV"

        L.info("Voltage output written to %s", voltage_file)
