"""Catalogue of bluepyefe protocols and eFEL features as Pydantic models.

Replaces the flat ``EFEATURE_CATALOGUE_BY_PROTOCOL`` dict-of-strings: each
feature is a Pydantic subclass of :class:`EFeature` carrying its own tunable
parameters (in :mod:`.efeatures`), and each protocol is a subclass of
:class:`Protocol` declaring which features it can extract (in
:mod:`.protocols`).
"""

from obi_one.scientific.tasks.emodel_optimization.task1_efeature_extraction.protocols_and_features.efeatures import (  # noqa: E501
    ISICV,
    AdaptationIndex,
    AHPDepth,
    AHPTimeFromPeak,
    AP1Amp,
    APAmplitude,
    APBeginVoltage,
    APBeginWidth,
    APDurationHalfWidth,
    DecayTimeConstantAfterStim,
    DepolBlockBool,
    DoubletISI,
    EFeature,
    InvFirstISI,
    InvLastISI,
    InvSecondISI,
    InvThirdISI,
    InvTimeToFirstSpike,
    IrregularityIndex,
    ISILogSlope,
    MeanFrequency,
    MinAHPValues,
    NumberInitialSpikes,
    OhmicInputResistanceVbSsse,
    SagAmplitude,
    SagRatio1,
    SagRatio2,
    Spikecount,
    StrictBurstMeanFreq,
    StrictBurstNumber,
    TimeToFirstSpike,
    TimeToLastSpike,
    VoltageAfterStim,
    VoltageBase,
)
from obi_one.scientific.tasks.emodel_optimization.task1_efeature_extraction.protocols_and_features.protocols import (  # noqa: E501
    IV,
    PROTOCOL_CATALOGUE,
    SAHP,
    APWaveform,
    IDhyperpol,
    IDrest,
    IDthresh,
    Protocol,
    ProtocolUnion,
    available_features_by_protocol_name,
)

__all__ = [
    "ISICV",
    "IV",
    "PROTOCOL_CATALOGUE",
    "SAHP",
    "AHPDepth",
    "AHPTimeFromPeak",
    "AP1Amp",
    "APAmplitude",
    "APBeginVoltage",
    "APBeginWidth",
    "APDurationHalfWidth",
    "APWaveform",
    "AdaptationIndex",
    "DecayTimeConstantAfterStim",
    "DepolBlockBool",
    "DoubletISI",
    "EFeature",
    "IDhyperpol",
    "IDrest",
    "IDthresh",
    "ISILogSlope",
    "InvFirstISI",
    "InvLastISI",
    "InvSecondISI",
    "InvThirdISI",
    "InvTimeToFirstSpike",
    "IrregularityIndex",
    "MeanFrequency",
    "MinAHPValues",
    "NumberInitialSpikes",
    "OhmicInputResistanceVbSsse",
    "Protocol",
    "ProtocolUnion",
    "SagAmplitude",
    "SagRatio1",
    "SagRatio2",
    "Spikecount",
    "StrictBurstMeanFreq",
    "StrictBurstNumber",
    "TimeToFirstSpike",
    "TimeToLastSpike",
    "VoltageAfterStim",
    "VoltageBase",
    "available_features_by_protocol_name",
]
