"""Tests for the launch-script obi-one pin tool and the shared regexes.

``launch_deps_pin`` / ``launch_deps_common`` are standalone modules under
``launch_scripts/tools/``, importable here via the ``pythonpath`` pytest setting.
"""

import launch_deps_common
import launch_deps_pin
import pytest

VERSION = "2026.9.15"

TXT = (
    "# This file was autogenerated from default.in by ...\n"
    "obi-one[connectivity]\n"
    "aiofiles==25.1.0\n"
    "numpy==2.4.6 ; sys_platform == 'linux'\n"
)


class TestReleaseVersionRegex:
    @pytest.mark.parametrize("version", ["2026.9.15", "2026.12.1", "2026.1.0"])
    def test_accepts_clean_calver(self, version):
        assert launch_deps_common.RELEASE_VERSION_REGEX.match(version)

    @pytest.mark.parametrize(
        "version",
        ["v2026.9.1", "2026.9.1-3-gabc", "2026.9", "2026.9.1.dev3", "26.9.1", "", "2026.9.1 "],
    )
    def test_rejects_non_release(self, version):
        assert not launch_deps_common.RELEASE_VERSION_REGEX.match(version)


class TestReleasePinRegex:
    def test_captures_version(self):
        m = launch_deps_common.RELEASE_PIN_REGEX.match("==2026.9.15")
        assert m
        assert m.group("version") == "2026.9.15"

    @pytest.mark.parametrize("spec", ["==2026.9", ">=2026.9.1", "== 2026.9.1", "==2026.9.1.dev3"])
    def test_rejects_other_specs(self, spec):
        assert not launch_deps_common.RELEASE_PIN_REGEX.match(spec)


class TestObiOneLineRegex:
    @pytest.mark.parametrize(
        ("line", "extras", "spec"),
        [
            ("obi-one", None, None),
            ("obi_one", None, None),
            ("obi-one[connectivity,emodel]", "connectivity,emodel", None),
            ("obi-one[emodel]==2026.9.1", "emodel", "==2026.9.1"),
            (
                "obi-one @ git+https://github.com/o/r.git@abc",
                None,
                "@ git+https://github.com/o/r.git@abc",
            ),
        ],
    )
    def test_parses(self, line, extras, spec):
        m = launch_deps_common.OBI_ONE_LINE_REGEX.match(line)
        assert m
        assert m.group("extras") == extras
        assert m.group("spec") == spec

    @pytest.mark.parametrize("line", ["obi-one-extra", "obi-one-tools==1.0", "numpy"])
    def test_other_packages_do_not_match(self, line):
        assert not launch_deps_common.OBI_ONE_LINE_REGEX.match(line)


class TestPinText:
    def test_pins_extras_line_and_keeps_everything_else(self):
        result, count = launch_deps_pin.pin_text(TXT, VERSION)
        assert count == 1
        assert result == TXT.replace(
            "obi-one[connectivity]\n", f"obi-one[connectivity]=={VERSION}\n"
        )

    @pytest.mark.parametrize("name", ["obi-one", "obi_one"])
    def test_pins_bare_name(self, name):
        result, count = launch_deps_pin.pin_text(f"{name}\nnumpy==2.0\n", VERSION)
        assert count == 1
        assert result == f"{name}=={VERSION}\nnumpy==2.0\n"

    def test_preserves_crlf_and_missing_final_newline(self):
        result, _ = launch_deps_pin.pin_text("numpy==2.0\r\nobi-one", VERSION)
        assert result == f"numpy==2.0\r\nobi-one=={VERSION}"

    @pytest.mark.parametrize(
        "line", ["obi-one[connectivity]==2026.9.1", "obi-one[connectivity]==2026.9.1  "]
    )
    def test_repins_previous_release(self, line):
        result, count = launch_deps_pin.pin_text(f"{line}\nnumpy==2.0\n", VERSION)
        assert count == 1
        assert result == f"obi-one[connectivity]=={VERSION}\nnumpy==2.0\n"

    def test_same_version_is_unchanged(self):
        text = f"obi-one[emodel]=={VERSION}\n"
        assert launch_deps_pin.pin_text(text, VERSION) == (text, 1)

    def test_no_obi_one_line(self):
        assert launch_deps_pin.pin_text("numpy==2.0\n", VERSION) == ("numpy==2.0\n", 0)

    def test_similarly_named_package_untouched(self):
        text = "obi-one-tools==1.0\n"
        assert launch_deps_pin.pin_text(text, VERSION) == (text, 0)

    @pytest.mark.parametrize(
        "line",
        [
            "obi-one==2026.9",
            "obi-one[emodel]>=2026.1.1",
            "obi-one ; python_version >= '3.12'",
            "obi-one[connectivity] @ git+https://github.com/openbraininstitute/obi-one.git@abc",
            "obi-one  # inline comment",
        ],
    )
    def test_rejects_unpinnable_lines(self, line):
        with pytest.raises(launch_deps_pin.PinError, match="refusing to pin"):
            launch_deps_pin.pin_text(f"numpy==2.0\n{line}\n", VERSION)


class TestPinFiles:
    def test_pins_only_files_with_obi_one(self, tmp_path):
        with_obi = tmp_path / "a.txt"
        with_obi.write_text("obi-one[emodel]\n", encoding="utf-8")
        without_obi = tmp_path / "b.txt"
        without_obi.write_text("numpy==2.0\n", encoding="utf-8")
        result = launch_deps_pin.pin_files([with_obi, without_obi], VERSION)
        assert result == {with_obi: f"obi-one[emodel]=={VERSION}\n"}

    @pytest.mark.parametrize("version", ["v2026.9.1", "2026.9.1-3-gabc", "2026.9"])
    def test_invalid_version(self, tmp_path, version):
        f = tmp_path / "a.txt"
        f.write_text("obi-one\n", encoding="utf-8")
        with pytest.raises(SystemExit, match="Invalid release version"):
            launch_deps_pin.pin_files([f], version)

    def test_no_obi_one_anywhere(self, tmp_path):
        f = tmp_path / "a.txt"
        f.write_text("numpy==2.0\n", encoding="utf-8")
        with pytest.raises(SystemExit, match="No obi-one requirement line"):
            launch_deps_pin.pin_files([f], VERSION)

    def test_error_reports_file(self, tmp_path):
        f = tmp_path / "a.txt"
        f.write_text("obi-one>=2026.1.1\n", encoding="utf-8")
        with pytest.raises(SystemExit, match=r"a\.txt"):
            launch_deps_pin.pin_files([f], VERSION)


class TestMain:
    def test_writes_all_files(self, tmp_path):
        a = tmp_path / "x" / "dependencies" / "a.txt"
        a.parent.mkdir(parents=True)
        a.write_text("obi-one\nnumpy==2.0\n", encoding="utf-8")
        b = tmp_path / "x" / "dependencies" / "b.txt"
        b.write_text("obi-one[emodel]\r\n", encoding="utf-8", newline="")
        assert launch_deps_pin.main(["--version", VERSION, str(tmp_path)]) == 0
        assert a.read_text(encoding="utf-8") == f"obi-one=={VERSION}\nnumpy==2.0\n"
        assert b.read_bytes() == f"obi-one[emodel]=={VERSION}\r\n".encode()

    def test_repin_writes_only_changed_files(self, tmp_path, capsys):
        a = tmp_path / "a.txt"
        a.write_text("obi-one==2026.9.1\n", encoding="utf-8")
        b = tmp_path / "b.txt"
        b.write_text(f"obi-one=={VERSION}\n", encoding="utf-8")
        assert launch_deps_pin.main(["--version", VERSION, str(tmp_path)]) == 0
        assert a.read_text(encoding="utf-8") == f"obi-one=={VERSION}\n"
        out = capsys.readouterr().out
        assert f"pinned obi-one=={VERSION}: {a}" in out
        assert f"already pinned: {b}" in out

    def test_check_passes_when_pinned(self, tmp_path):
        f = tmp_path / "a.txt"
        f.write_text(f"obi-one[emodel]=={VERSION}\n", encoding="utf-8")
        assert launch_deps_pin.main(["--check", "--version", VERSION, str(tmp_path)]) == 0

    @pytest.mark.parametrize("line", ["obi-one[emodel]", "obi-one[emodel]==2026.9.1"])
    def test_check_fails_and_writes_nothing(self, tmp_path, capsys, line):
        f = tmp_path / "a.txt"
        f.write_text(f"{line}\n", encoding="utf-8")
        assert launch_deps_pin.main(["--check", "--version", VERSION, str(tmp_path)]) == 1
        assert f.read_text(encoding="utf-8") == f"{line}\n"
        assert f"NOT PINNED to obi-one=={VERSION}: {f}" in capsys.readouterr().err

    def test_writes_nothing_on_error(self, tmp_path):
        good = tmp_path / "good.txt"
        good.write_text("obi-one\n", encoding="utf-8")
        bad = tmp_path / "bad.txt"
        bad.write_text("obi-one @ git+https://example.org/x.git\n", encoding="utf-8")
        with pytest.raises(SystemExit):
            launch_deps_pin.main(["--version", VERSION, str(tmp_path)])
        assert good.read_text(encoding="utf-8") == "obi-one\n"

    def test_default_paths_cover_repo_launch_files(self):
        files = launch_deps_pin.resolve_txt_files([])
        assert files
        assert all(p.parent.name == "dependencies" and p.suffix == ".txt" for p in files)

    def test_rejects_non_txt_path(self, tmp_path):
        f = tmp_path / "a.in"
        f.write_text("obi-one\n", encoding="utf-8")
        with pytest.raises(SystemExit, match=r"Not a \.txt file or directory"):
            launch_deps_pin.resolve_txt_files([str(f)])

    def test_repo_files_are_pinnable(self):
        # Committed launch-script .txt files must stay bare or pinned to a release,
        # or the release-pin workflow would fail at release time.
        pinned = launch_deps_pin.pin_files(launch_deps_pin.resolve_txt_files([]), VERSION)
        assert pinned
