"""Shared helpers for circuit registration and customization endpoints."""

import logging
from uuid import UUID

import entitysdk.client
import httpx
from entitysdk.types import EntityLifecycleStatus, EntityType

from app.config import settings
from app.errors import internal_error
from obi_one.db_sdk.db_sdk import get_execution_activity
from obi_one.db_sdk.registration.circuit.launch_jobs import (
    submit_circuit_asset_generation_job,
    submit_circuit_validation_job,
)

L = logging.getLogger(__name__)


def trigger_validation_task(
    *,
    ls_client: httpx.Client,
    circuit_id: UUID,
    project_id: UUID,
    virtual_lab_id: UUID,
    compute_cell: str,
    force: bool = False,
    generate_assets_on_success: bool = True,
) -> UUID | None:
    """Submit a circuit validation job to the launch-system.

    Args:
        ls_client: Launch-system HTTP client.
        circuit_id: Circuit entity ID to validate.
        project_id: Project ID for the job.
        virtual_lab_id: Virtual lab ID for the job.
        compute_cell: Compute cell for the launch-system job (from the vlab).
        force: When True, validate even if the circuit is not in ``draft`` status.
        generate_assets_on_success: When True, trigger asset generation after a
            successful validation. Disable for standalone re-validation.

    Returns:
        Launch-system job ID if accepted, otherwise ``None``.
    """
    return submit_circuit_validation_job(
        ls_client=ls_client,
        circuit_id=circuit_id,
        project_id=project_id,
        virtual_lab_id=virtual_lab_id,
        api_url=settings.API_URL,
        compute_cell=compute_cell,
        obi_one_repo=settings.OBI_ONE_REPO,
        app_version=settings.APP_VERSION,
        force=force,
        generate_assets_on_success=generate_assets_on_success,
    )


def trigger_asset_generation_task(
    *,
    ls_client: httpx.Client,
    circuit_id: UUID,
    project_id: UUID,
    virtual_lab_id: UUID,
    compute_cell: str,
    force: bool = False,
) -> UUID | None:
    """Submit an asset generation job to the launch-system.

    Args:
        ls_client: Launch-system HTTP client.
        circuit_id: Circuit entity ID to generate assets for.
        project_id: Project ID for the job.
        virtual_lab_id: Virtual lab ID for the job.
        compute_cell: Compute cell for the launch-system job (from the vlab).
        force: When True, regenerate compressed archive even if it already exists.

    Returns:
        Launch-system job ID if accepted, otherwise ``None``.
    """
    return submit_circuit_asset_generation_job(
        ls_client=ls_client,
        circuit_id=circuit_id,
        project_id=project_id,
        virtual_lab_id=virtual_lab_id,
        compute_cell=compute_cell,
        obi_one_repo=settings.OBI_ONE_REPO,
        app_version=settings.APP_VERSION,
        force=force,
    )


def trigger_validation_for_generated_circuits(
    *,
    db_client: entitysdk.client.Client,
    ls_client: httpx.Client,
    activity_id: UUID,
    compute_cell: str,
) -> list[UUID]:
    """Submit validation job per draft circuit generated by task activity.

    Runs on task job success (see ``TaskDefinition.async_circuit_validation``).
    Non-draft circuits skipped. Every draft gets submission attempt; any failure then
    raises internal API error, so launch-system marks callback failed and draft not
    stuck silently.

    Args:
        db_client: EntitySDK client with task project context.
        ls_client: Launch-system HTTP client.
        activity_id: Task execution activity ID.
        compute_cell: Compute cell for validation jobs (from vlab).

    Returns:
        Launch-system job IDs of submitted validation jobs.
    """
    activity = get_execution_activity(client=db_client, execution_activity_id=activity_id)
    draft_circuit_ids = [
        entity.id
        for entity in activity.generated or []
        if entity.type == EntityType.circuit
        and entity.lifecycle_status == EntityLifecycleStatus.draft
    ]
    job_ids: list[UUID] = []
    failed_circuit_ids: list[UUID] = []
    for circuit_id in draft_circuit_ids:
        job_id = trigger_validation_task(
            ls_client=ls_client,
            circuit_id=circuit_id,
            project_id=db_client.project_context.project_id,  # ty:ignore[unresolved-attribute]
            virtual_lab_id=db_client.project_context.virtual_lab_id,  # ty:ignore[unresolved-attribute, invalid-argument-type]
            compute_cell=compute_cell,
        )
        if job_id is None:
            failed_circuit_ids.append(circuit_id)
        else:
            job_ids.append(job_id)
    if failed_circuit_ids:
        msg = f"Failed to submit the validation job for circuits {failed_circuit_ids}."
        raise internal_error(msg)
    return job_ids
