name: Build and publish the Docker image

permissions:
  id-token: write # Required for OIDC authentication
  contents: read # Standard permission for GitHub Actions

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-to-aws-ecr:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: prod

    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Authenticate with AWS CodeArtifact account
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::985539765147:role/gh_codeartifact_read_all
          aws-region: us-east-1

      - name: Get CodeArtifact token
        run: |
          CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token \
            --domain openbraininstitute \
            --query authorizationToken \
            --output text)
          echo "::add-mask::$CODEARTIFACT_AUTH_TOKEN"
          echo "UV_INDEX_OBI_CODEARTIFACT_PASSWORD=$CODEARTIFACT_AUTH_TOKEN" >> $GITHUB_ENV
          echo "UV_INDEX_OBI_CODEARTIFACT_USERNAME=aws" >> $GITHUB_ENV
          echo "CODEARTIFACT_TOKEN=$CODEARTIFACT_AUTH_TOKEN" >> $GITHUB_ENV

      - name: Authenticate with AWS ECR account for pushing the image
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::985539765147:role/gh_ecr_push_obi-one-private
          aws-region: us-east-1

      - name: Authenticate with AWS ECR
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Build, tag and push container
        env:
          IMAGE_NAME: ${{ steps.login-ecr.outputs.registry }}/obi-one
        run: |-
          make publish
